import type { KreuzwortraetselPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Wort-Pool für das Kreuzworträtsel „Immobilienfachwirt".
 * 34 kurze, alltagsnahe Begriffe aus allen sechs Fachgebieten (HB1 Rahmenbedingungen, HB2 Rechnungswesen/Controlling/Risiko,
 * HB3 Personal/Organisation, HB4 Bewirtschaftung, HB5 Bau und Projekt, HB6 Vermarktung). Der Server zieht je Start zehn Wörter und
 * legt das Gitter selbst an (daher keine Positionen/Richtungen). Bewusst ohne Rechtsdetails (keine Paragrafen, Fristen, Zahlen).
 * Entwurf — bis zur Fachprüfung gesperrt.
 */
export const kreuzwortraetselImmobilien: KreuzwortraetselPayload = {
  wortzahl: 10,
  woerter: [
    {
      nummer: 1,
      hinweis: "Amtliches Verzeichnis, in dem Eigentümer und Belastungen eines Grundstücks stehen.",
      tipp: "Ein Auszug daraus wird vor der Vermarktung geprüft.",
      loesung: "GRUNDBUCH",
      bestaetigung: "Genau! Im Grundbuch sind Eigentümer und Belastungen eines Grundstücks eingetragen.",
    },
    {
      nummer: 2,
      hinweis: "Sie oder er vermittelt Kauf-, Miet- oder Pachtverträge zwischen zwei Seiten.",
      tipp: "Zeigt Interessenten Objekte bei der Besichtigung.",
      loesung: "MAKLER",
      bestaetigung: "Richtig! Makler bringen Anbieter und Interessenten zusammen und vermitteln Verträge.",
    },
    {
      nummer: 3,
      hinweis: "Person oder Firma, die Kapital in Immobilien anlegt.",
      tipp: "Versicherungen und Fonds zählen oft dazu.",
      loesung: "INVESTOR",
      bestaetigung: "Genau! Investoren legen Kapital in Immobilien an, privat oder als große Institution.",
    },
    {
      nummer: 4,
      hinweis: "Unternehmen, das Projekte auf eigenes Risiko entwickelt, baut und verkauft.",
      tipp: "Ravelin hat dafür eine eigene Sparte.",
      loesung: "BAUTRAEGER",
      bestaetigung: "Richtig! Ein Bauträger entwickelt und errichtet Projekte auf eigenes wirtschaftliches Risiko.",
    },
    {
      nummer: 5,
      hinweis: "Schicht an Wand oder Dach, die Wärmeverluste eines Gebäudes verringert.",
      tipp: "Typische Maßnahme bei der energetischen Sanierung.",
      loesung: "DAEMMUNG",
      bestaetigung: "Genau! Die Wärmedämmung der Gebäudehülle ist eine typische Maßnahme der energetischen Sanierung.",
    },
    {
      nummer: 6,
      hinweis: "Der Wunsch von Interessenten, Wohnungen oder Flächen zu mieten oder zu kaufen.",
      tipp: "Das Gegenstück zum Angebot.",
      loesung: "NACHFRAGE",
      bestaetigung: "Richtig! Steigt die Nachfrage bei knappem Angebot, ziehen die Preise tendenziell an.",
    },
    {
      nummer: 7,
      hinweis: "Teil des Jahresabschlusses, neben Gewinn- und Verlustrechnung und Anhang.",
      tipp: "Anfangsbuchstabe B, sechs Buchstaben.",
      loesung: "BILANZ",
      bestaetigung: "Genau! Die Bilanz gehört zum Jahresabschluss einer GmbH wie der Ravelin Immobilien GmbH.",
    },
    {
      nummer: 8,
      hinweis: "Kennzahl für den Ertrag einer Immobilie im Verhältnis zum Kaufpreis.",
      tipp: "Brutto, netto oder als Objektwert gerechnet.",
      loesung: "RENDITE",
      bestaetigung: "Richtig! Die Rendite zeigt, wie gut sich das eingesetzte Geld verzinst.",
    },
    {
      nummer: 9,
      hinweis: "Mögliche Gefahr, die Erfolg oder Geld eines Projekts bedroht.",
      tipp: "Wird nach Wahrscheinlichkeit und Schaden bewertet.",
      loesung: "RISIKO",
      bestaetigung: "Genau! Risiken werden erkannt, bewertet, gesteuert und überwacht.",
    },
    {
      nummer: 10,
      hinweis: "Zustand einer Wohnung oder Fläche, die gerade nicht vermietet ist.",
      tipp: "Eine Quote misst, wie viele Einheiten betroffen sind.",
      loesung: "LEERSTAND",
      bestaetigung: "Richtig! Leerstand bedeutet fehlende Mieteinnahmen und wird im Controlling beobachtet.",
    },
    {
      nummer: 11,
      hinweis: "Geld, das eine Bank gegen Zinsen verleiht, etwa für den Kauf einer Immobilie.",
      tipp: "Das Annuitätendarlehen ist eine Form davon.",
      loesung: "KREDIT",
      bestaetigung: "Richtig! Immobilien werden meist mit einer Mischung aus Eigenkapital und Fremdkapital wie einem Kredit finanziert.",
    },
    {
      nummer: 12,
      hinweis: "Fähigkeit, fällige Zahlungen jederzeit leisten zu können.",
      tipp: "Wird in drei Graden gemessen.",
      loesung: "LIQUIDITAET",
      bestaetigung: "Richtig! Liquidität heißt, fällige Zahlungen rechtzeitig leisten zu können.",
    },
    {
      nummer: 13,
      hinweis: "Antrieb, eine Leistung zu zeigen — von innen oder von außen angeregt.",
      tipp: "Anerkennung und Verantwortung steigern sie.",
      loesung: "MOTIVATION",
      bestaetigung: "Genau! Nach Herzberg steigern Anerkennung und Verantwortung die Motivation.",
    },
    {
      nummer: 14,
      hinweis: "Individuelle Begleitung einer Person bei besonderen Herausforderungen.",
      tipp: "Hilft zum Beispiel angehenden Führungskräften.",
      loesung: "COACHING",
      bestaetigung: "Richtig! Coaching begleitet einzelne Personen gezielt bei ihrer Entwicklung.",
    },
    {
      nummer: 15,
      hinweis: "Erfahrene Beschäftigte begleiten neue Kolleginnen und Kollegen.",
      tipp: "Anfangsbuchstabe M, neun Buchstaben.",
      loesung: "MENTORING",
      bestaetigung: "Genau! Beim Mentoring geben Erfahrene ihr Wissen an Neue weiter.",
    },
    {
      nummer: 16,
      hinweis: "Zeichnung, die zeigt, welche Stellen und Abteilungen es gibt und wie sie zusammenhängen.",
      tipp: "Bildet den Aufbau eines Unternehmens ab.",
      loesung: "ORGANIGRAMM",
      bestaetigung: "Richtig! Das Organigramm stellt die Aufbauorganisation eines Unternehmens dar.",
    },
    {
      nummer: 17,
      hinweis: "Festgelegte Abfolge von Schritten, etwa von der Mängelmeldung bis zum Handwerker.",
      tipp: "Die Ablauforganisation regelt ihn.",
      loesung: "PROZESS",
      bestaetigung: "Genau! Klare Prozesse vermeiden Doppelarbeit und machen Zuständigkeiten sichtbar.",
    },
    {
      nummer: 18,
      hinweis: "Regelmäßige Maßnahme, die den Sollzustand einer Anlage bewahrt.",
      tipp: "Zum Beispiel für die Heizung.",
      loesung: "WARTUNG",
      bestaetigung: "Richtig! Wartung bewahrt den Sollzustand, Instandsetzung stellt ihn nach einem Mangel wieder her.",
    },
    {
      nummer: 19,
      hinweis: "Feststellen und Beurteilen des Ist-Zustands, zum Beispiel bei einer Dachbegehung.",
      tipp: "Schauen und beurteilen, noch nicht reparieren.",
      loesung: "INSPEKTION",
      bestaetigung: "Genau! Bei einer Inspektion wird der Ist-Zustand festgestellt und beurteilt.",
    },
    {
      nummer: 20,
      hinweis: "Fachbetrieb, den die Hausverwaltung für Reparaturen beauftragt.",
      tipp: "Von ihm holt man vorher ein Angebot ein.",
      loesung: "HANDWERKER",
      bestaetigung: "Richtig! Handwerker werden ausgewählt, koordiniert und ihre Arbeit wird abgenommen.",
    },
    {
      nummer: 21,
      hinweis: "Technische Anlage im Haus, die Personen in andere Etagen bringt.",
      tipp: "Auch Fahrstuhl genannt.",
      loesung: "AUFZUG",
      bestaetigung: "Genau! Aufzüge gehören zur technischen Gebäudeausrüstung und brauchen Wartung.",
    },
    {
      nummer: 22,
      hinweis: "Person, die eine Wohnung gegen regelmäßige Zahlung nutzt.",
      tipp: "Meldet zum Beispiel einen Wasserschaden.",
      loesung: "MIETER",
      bestaetigung: "Richtig! Mieter nutzen die Wohnung, die Hausverwaltung betreut sie für die Eigentümer.",
    },
    {
      nummer: 23,
      hinweis: "Plötzlicher Schaden an einer Leitung, bei dem Wasser austritt.",
      tipp: "Muss sofort bearbeitet werden.",
      loesung: "ROHRBRUCH",
      bestaetigung: "Genau! Ein Rohrbruch ist dringend und wichtig — also sofort erledigen.",
    },
    {
      nummer: 24,
      hinweis: "Erste Bauphase: Wände, Decken und tragende Teile, noch ohne Ausbau.",
      tipp: "Danach folgt der Innenausbau.",
      loesung: "ROHBAU",
      bestaetigung: "Richtig! Erst entsteht der Rohbau, dann folgen Dach und Innenausbau.",
    },
    {
      nummer: 25,
      hinweis: "Bereich handwerklicher Bauleistungen, zum Beispiel Elektro oder Sanitär.",
      tipp: "Sechs Buchstaben, beginnt mit G.",
      loesung: "GEWERK",
      bestaetigung: "Genau! Auf der Baustelle arbeiten viele Gewerke Hand in Hand.",
    },
    {
      nummer: 26,
      hinweis: "Grafik, die Vorgänge eines Projekts und ihre Abhängigkeiten als Netz zeigt.",
      tipp: "Daraus liest man den kritischen Pfad ab.",
      loesung: "NETZPLAN",
      bestaetigung: "Richtig! Im Netzplan sieht man, welche Vorgänge den Fertigstellungstermin bestimmen.",
    },
    {
      nummer: 27,
      hinweis: "Zeitlicher Spielraum eines Vorgangs, ohne das Projektende zu verschieben.",
      tipp: "Auf dem kritischen Pfad ist er null.",
      loesung: "PUFFER",
      bestaetigung: "Genau! Vorgänge mit Puffer dürfen sich verschieben, ohne das Projekt zu verzögern.",
    },
    {
      nummer: 28,
      hinweis: "Der Auftraggeber bestätigt, dass eine Bauleistung im Wesentlichen in Ordnung ist.",
      tipp: "Findet nach der Fertigstellung statt; Mängel werden notiert.",
      loesung: "ABNAHME",
      bestaetigung: "Richtig! Bei der Abnahme wird die Leistung geprüft und werden Mängel festgehalten.",
    },
    {
      nummer: 29,
      hinweis: "Zusage an die Firma, die nach der Angebotsprüfung den Auftrag erhält.",
      tipp: "Folgt auf Ausschreibung und Prüfung der Angebote.",
      loesung: "ZUSCHLAG",
      bestaetigung: "Genau! Erst nach der Prüfung von Preis, Eignung und Kapazität wird der Zuschlag erteilt.",
    },
    {
      nummer: 30,
      hinweis: "Erste Stufe im Vertrieb: neue Aufträge oder Objekte gewinnen.",
      tipp: "Danach werden die Anfragen qualifiziert.",
      loesung: "AKQUISE",
      bestaetigung: "Richtig! Am Anfang des Vertriebs steht die Akquise von Aufträgen.",
    },
    {
      nummer: 31,
      hinweis: "Zentrales Verkaufsdokument mit Lage, Ausstattung, Fläche, Preis und Bildern.",
      tipp: "Sechs Buchstaben, beginnt mit E.",
      loesung: "EXPOSE",
      bestaetigung: "Genau! Das Exposé fasst alle wichtigen Informationen zu einem Objekt zusammen.",
    },
    {
      nummer: 32,
      hinweis: "Maßstabsgerechte Zeichnung, die die Räume einer Wohnung von oben zeigt.",
      tipp: "Gehört zum Mindeststandard jeder Vermarktung.",
      loesung: "GRUNDRISS",
      bestaetigung: "Richtig! Ein aktueller Grundriss gehört zu jeder guten Objektpräsentation.",
    },
    {
      nummer: 33,
      hinweis: "Große Online-Plattform, auf der Immobilien gesucht und angeboten werden.",
      tipp: "Wichtigster Einzelkanal der Maklerabteilung.",
      loesung: "PORTAL",
      bestaetigung: "Genau! Immobilienportale bieten hohe Reichweite bei aktiv Suchenden.",
    },
    {
      nummer: 34,
      hinweis: "Zufriedene Kunden raten Bekannten zum Unternehmen.",
      tipp: "Eine wichtige Quelle für neue Kunden.",
      loesung: "EMPFEHLUNG",
      bestaetigung: "Richtig! Empfehlungen sind im Immobiliengeschäft eine der wichtigsten Quellen für neue Kunden.",
    },
  ],
  falschEinfachFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und vergleiche die Bedeutung mit den übrigen Begriffen.",
  falschAnspruchsvollFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und prüfe auch die Buchstaben an den Kreuzungen.",
  unvollstaendigFeedback: "Hier fehlen noch Buchstaben. Du kannst das Wort weiter ausfüllen.",
  abschlussmeldung:
    "Geschafft! Du hast zehn Begriffe aus der Immobilienwirtschaft erkannt — vom Grundbuch bis zum Netzplan. Jedes Rätsel ist anders — spiel gern noch eins!",
};
