import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Paar-Pool „Wirtschaftsfachwirt" für das Memory.
 * Vier thematische Runden mit je zehn Paaren (Begriff ↔ Bedeutung) aus der Kurstheorie (content/wirtschaftsfachwirt/);
 * das Spiel zieht je Runde sechs Paare. Verteilung: Runde 1 = WBQ1, Runde 2 = WBQ2 + HSQ2, Runde 3 = WBQ3 + WBQ4 + HSQ1,
 * Runde 4 = HSQ3 + HSQ4 + HSQ5. Keine Paragrafen, Zahlenwerte, Steuersätze oder Fristen.
 * Inhaltlicher Entwurf, bis zur Fachprüfung gesperrt.
 */
export const memoryWirtschaft: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Volks- und Betriebswirtschaft",
      abschlussmeldung: "Geschafft! Du kennst jetzt Marktformen, Konjunktur, Finanzierungsarten und Unternehmensformen besser.",
    },
    {
      nummer: 2,
      titel: "Rechnungswesen, Finanzierung und Controlling",
      abschlussmeldung: "Geschafft! Du erkennst jetzt zentrale Begriffe aus Rechnungswesen, Investition, Finanzierung und Controlling.",
    },
    {
      nummer: 3,
      titel: "Recht, Organisation und Management",
      abschlussmeldung: "Geschafft! Du kannst Grundbegriffe aus Handelsrecht, Organisation und Managementtechniken zuordnen.",
    },
    {
      nummer: 4,
      titel: "Logistik, Marketing und Zusammenarbeit",
      abschlussmeldung: "Geschafft! Du kennst jetzt wichtige Begriffe aus Beschaffung, Lager, Marketing, Gesprächsführung und Moderation.",
    },
  ],
  paareProRunde: 6,
  paare: [
    // Runde 1 — WBQ1
    {
      nummer: 1,
      runde: 1,
      begriff: "Polypol",
      bedeutung: "Viele Anbieter treffen auf viele Nachfrager",
      bestaetigung: "Richtig! Im Polypol kann kein einzelner Anbieter den Marktpreis nennenswert beeinflussen.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Oligopol",
      bedeutung: "Wenige große Anbieter beherrschen den Markt",
      bestaetigung: "Genau! Im Oligopol beeinflussen sich die Entscheidungen der Anbieter gegenseitig.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Gleichgewichtspreis",
      bedeutung: "Angebot und Nachfrage stimmen mengenmäßig überein",
      bestaetigung: "Richtig! Beim Gleichgewichtspreis ist der Markt „geräumt“.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Soziale Marktwirtschaft",
      bedeutung: "Freier Markt plus staatlicher Rahmen und Ausgleich",
      bestaetigung: "Genau! Sie verbindet den freien Preismechanismus mit einem staatlichen Ordnungsrahmen und sozialem Ausgleich.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Aufschwung",
      bedeutung: "Konjunkturphase mit steigender Produktion",
      bestaetigung: "Richtig! Im Aufschwung steigen Produktion, Beschäftigung und Auftragseingänge.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Just-in-Time",
      bedeutung: "Lieferung genau zum Bedarf, kaum Lagerbestand",
      bestaetigung: "Genau! Das spart Kapitalbindung, erhöht aber das Risiko bei Lieferstörungen.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Innenfinanzierung",
      bedeutung: "Mittel, die das Unternehmen selbst erwirtschaftet",
      bestaetigung: "Richtig! Ein Beispiel sind einbehaltene Gewinne.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Marketing-Mix",
      bedeutung: "Produkt-, Preis-, Distributions-, Kommunikationspolitik",
      bestaetigung: "Genau! Man nennt diese vier Bereiche auch die „vier P“.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Komplementär",
      bedeutung: "Haftet in der KG unbeschränkt und führt die Geschäfte",
      bestaetigung: "Richtig! Der Kommanditist haftet dagegen nur beschränkt.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Joint Venture",
      bedeutung: "Gemeinsam gegründetes Unternehmen mehrerer Partner",
      bestaetigung: "Genau! Ein Joint Venture dient oft dazu, gemeinsam neue Märkte zu erschließen.",
    },
    // Runde 2 — WBQ2 + HSQ2
    {
      nummer: 11,
      runde: 2,
      begriff: "Niederstwertprinzip",
      bedeutung: "Vorräte werden mit dem niedrigeren Wert angesetzt",
      bestaetigung: "Richtig! Es konkretisiert das Vorsichtsprinzip für das Umlaufvermögen.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Gewinn- und Verlustrechnung",
      bedeutung: "Stellt Erträge und Aufwendungen einer Periode gegenüber",
      bestaetigung: "Genau! So ergibt sich der Erfolg der Periode.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Zuschlagskalkulation",
      bedeutung: "Gemeinkosten werden über Zuschlagssätze aufgeschlagen",
      bestaetigung: "Richtig! Sie passt gut zu einem vielfältigen Sortiment.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Teilkostenrechnung",
      bedeutung: "Rechnet Kostenträgern nur die variablen Kosten zu",
      bestaetigung: "Genau! Die fixen Kosten werden als Block der Periode gegenübergestellt.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Soll-Ist-Vergleich",
      bedeutung: "Plan-Werte werden den tatsächlichen gegenübergestellt",
      bestaetigung: "Richtig! Er ist die zentrale Rückkopplungsschleife der Planungsrechnung.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Kapitalwert",
      bedeutung: "Alle Zahlungen einer Investition, auf heute abgezinst",
      bestaetigung: "Genau! Ein positiver Kapitalwert spricht für die Investition.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Amortisationsrechnung",
      bedeutung: "Zeit, bis der Anschaffungsbetrag zurückgeflossen ist",
      bestaetigung: "Richtig! Sie wird auch Pay-off-Methode genannt.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Selbstfinanzierung",
      bedeutung: "Nicht ausgeschüttete Gewinne bleiben im Unternehmen",
      bestaetigung: "Genau! Sie ist die wichtigste Form der Innenfinanzierung.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Factoring",
      bedeutung: "Verkauf von Forderungen gegen sofortiges Geld",
      bestaetigung: "Richtig! Das Unternehmen muss nicht auf das Zahlungsziel der Kundschaft warten.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Balanced Scorecard",
      bedeutung: "Kennzahlen aus vier Perspektiven, nicht nur Finanzen",
      bestaetigung: "Genau! Sie ergänzt finanzielle Kennzahlen um Kunden, Prozesse sowie Lernen und Entwicklung.",
    },
    // Runde 3 — WBQ3 + WBQ4 + HSQ1
    {
      nummer: 21,
      runde: 3,
      begriff: "Handelsregister",
      bedeutung: "Öffentliches Verzeichnis über Kaufleute und Firmen",
      bestaetigung: "Richtig! Dort stehen unter anderem Firma, Sitz und vertretungsberechtigte Personen.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Handlungsvollmacht",
      bedeutung: "Vollmacht nur für gewöhnliche Geschäfte eines Betriebs",
      bestaetigung: "Genau! Sie ist enger gefasst als die Prokura.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "Nacherfüllung",
      bedeutung: "Nachbesserung oder Nachlieferung bei einem Mangel",
      bestaetigung: "Richtig! Sie ist beim Kauf das vorrangige Recht, bevor Rücktritt oder Minderung greifen.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Ablauforganisation",
      bedeutung: "Regelt, wie Arbeitsschritte zeitlich ablaufen",
      bestaetigung: "Genau! Die Aufbauorganisation klärt dagegen, wer wofür zuständig ist.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Stabsstelle",
      bedeutung: "Berät eine Instanz, entscheidet aber nicht selbst",
      bestaetigung: "Richtig! Stabsstellen haben keine Leitungsbefugnis.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Leitungsspanne",
      bedeutung: "Anzahl der einer Instanz direkt unterstellten Stellen",
      bestaetigung: "Genau! Ist sie zu groß, wird die Führungskraft überlastet.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Laissez-faire-Führungsstil",
      bedeutung: "Mitarbeitende haben viel Freiheit, kaum Steuerung",
      bestaetigung: "Richtig! Das kann bei selbstständigen Teams gut funktionieren, birgt aber Orientierungslosigkeit.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Eisenhower-Prinzip",
      bedeutung: "Aufgaben nach Dringlichkeit und Wichtigkeit einteilen",
      bestaetigung: "Genau! Daraus ergibt sich, was sofort erledigt, terminiert oder delegiert wird.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Auftauen (Unfreeze)",
      bedeutung: "Erste Lewin-Phase: Bereitschaft zum Wandel schaffen",
      bestaetigung: "Richtig! Danach folgen Verändern und Einfrieren.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Benchmarking",
      bedeutung: "Vergleich mit anderen Unternehmen oder Standorten",
      bestaetigung: "Genau! Es ist ein Instrument der Organisationsanalyse.",
    },
    // Runde 4 — HSQ3 + HSQ4 + HSQ5
    {
      nummer: 31,
      runde: 4,
      begriff: "ABC-Analyse",
      bedeutung: "Einteilung der Güter nach ihrem Wertanteil am Einkauf",
      bestaetigung: "Richtig! A-Güter haben einen hohen Wertanteil und verdienen besonders viel Planung.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Sicherheitsbestand",
      bedeutung: "Puffer gegen Schwankungen und späte Lieferungen",
      bestaetigung: "Genau! Er sollte höher sein, wenn der Verbrauch unregelmäßig ist.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Single Sourcing",
      bedeutung: "Nur ein einziger Lieferant je Artikel",
      bestaetigung: "Richtig! Das ermöglicht enge Partnerschaften, birgt aber ein hohes Abhängigkeitsrisiko.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Skimmingstrategie",
      bedeutung: "Hoher Startpreis, der schrittweise sinkt",
      bestaetigung: "Genau! So werden zuerst weniger preissensible Kundengruppen abgeschöpft.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Cross-Selling",
      bedeutung: "Ergänzende Produkte an Bestandskunden anbieten",
      bestaetigung: "Richtig! Ein CRM-System hilft, solche Chancen gezielt zu erkennen.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Key-Account-Management",
      bedeutung: "Persönliche Betreuung der wichtigsten Kunden",
      bestaetigung: "Genau! Feste Ansprechpersonen betreuen diese Schlüsselkunden individuell.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Ich-Botschaft",
      bedeutung: "Aussage aus eigener Sicht, weniger vorwurfsvoll",
      bestaetigung: "Richtig! Sie lässt mehr Raum für eine sachliche Klärung als eine Du-Botschaft.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Paraphrasieren",
      bedeutung: "Gehörtes in eigenen Worten wiedergeben",
      bestaetigung: "Genau! So prüft man, ob man das Gegenüber richtig verstanden hat.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Kartenabfrage",
      bedeutung: "Ideen einzeln auf Karten schreiben, dann gruppieren",
      bestaetigung: "Richtig! So beteiligen sich auch zurückhaltende Personen gleichberechtigt.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Vier-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen lassen, Üben",
      bestaetigung: "Genau! Sie hat sich für die praktische Wissensvermittlung in der Ausbildung bewährt.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus dem ganzen Wirtschaftsfachwirt zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten — so festigst du, was du kannst.",
};
