import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Paar-Pool für das Memory „Immobilienfachwirt".
 * Vier thematische Runden mit je zehn Paaren (je Spiel werden sechs gezogen). Verteilung über die Fachgebiete:
 * Runde 1 = HB1, Runde 2 = HB2, Runde 3 = HB3 und HB4, Runde 4 = HB5 und HB6.
 * Bewusst ohne Rechtsdetails (keine Paragrafen, Fristen, Zahlen). Entwurf — bis zur Fachprüfung gesperrt.
 */
export const memoryImmobilien: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Markt, Akteure und Nachhaltigkeit",
      abschlussmeldung: "Geschafft! Du kennst jetzt wichtige Marktsegmente, Rollen und Begriffe der Immobilienwirtschaft.",
    },
    {
      nummer: 2,
      titel: "Zahlen, Finanzierung und Risiko",
      abschlussmeldung: "Geschafft! Du kannst Kennzahlen, Rechenverfahren und Werkzeuge des Risikomanagements zuordnen.",
    },
    {
      nummer: 3,
      titel: "Personal, Organisation und Bewirtschaftung",
      abschlussmeldung: "Geschafft! Du erkennst Begriffe aus Führung, Organisation und Instandhaltung.",
    },
    {
      nummer: 4,
      titel: "Bauprojekt und Vermarktung",
      abschlussmeldung: "Geschafft! Du kennst jetzt zentrale Begriffe aus Bauablauf, Terminplanung und Vermarktung.",
    },
  ],
  paareProRunde: 6,
  paare: [
    {
      nummer: 1,
      runde: 1,
      begriff: "Wohnimmobilie",
      bedeutung: "Dient dem dauerhaften Wohnen von Privatpersonen",
      bestaetigung: "Richtig! Wohnimmobilien sind Gebäude, in denen Menschen dauerhaft wohnen.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Gewerbeimmobilie",
      bedeutung: "Büro, Handel oder Logistik für Unternehmen",
      bestaetigung: "Genau! Gewerbeimmobilien dienen der betrieblichen Nutzung durch Unternehmen.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Sonderimmobilie",
      bedeutung: "Zum Beispiel Hotel oder Pflegeeinrichtung",
      bestaetigung: "Richtig! Sonderimmobilien haben eigene Nutzungsanforderungen und Betreiberkonzepte.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Nutzermarkt",
      bedeutung: "Angebot und Nachfrage nach Vermietung von Flächen",
      bestaetigung: "Genau! Im Nutzermarkt geht es um die Vermietung und Nutzung von Flächen.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Investmentmarkt",
      bedeutung: "Kauf und Verkauf von Immobilien als Kapitalanlage",
      bestaetigung: "Richtig! Der Investmentmarkt handelt Immobilien als Geldanlage.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Property Management",
      bedeutung: "Operative Bewirtschaftung einzelner Objekte",
      bestaetigung: "Genau! Property Management kümmert sich um das Tagesgeschäft eines Objekts, etwa Vermietung und Instandhaltung.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Asset Management",
      bedeutung: "Strategische Steuerung eines ganzen Portfolios",
      bestaetigung: "Richtig! Asset Management steuert Rendite und Wertentwicklung des gesamten Bestands.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Grundbuch",
      bedeutung: "Amtliches Register über Eigentümer und Belastungen",
      bestaetigung: "Genau! Im Grundbuch stehen Eigentümer und Belastungen eines Grundstücks.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "PropTech",
      bedeutung: "Digitale Plattformen und Technik für Immobilien",
      bestaetigung: "Richtig! PropTech verbindet „Property“ und „Technology“.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "ESG",
      bedeutung: "Umwelt, Soziales und Unternehmensführung",
      bestaetigung: "Genau! ESG steht für Environmental, Social und Governance — Kriterien für nachhaltiges Wirtschaften.",
    },
    {
      nummer: 11,
      runde: 2,
      begriff: "Kostenvergleichsrechnung",
      bedeutung: "Vergleicht die Durchschnittskosten von Alternativen",
      bestaetigung: "Richtig! Sie ist ein einfaches statisches Verfahren und eignet sich, wenn die Erträge gleich sind.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Amortisationsrechnung",
      bedeutung: "Fragt, wann sich eine Investition zurückgezahlt hat",
      bestaetigung: "Genau! Sie zeigt, nach welcher Zeit die Rückflüsse die Investition ausgleichen.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Kapitalwertmethode",
      bedeutung: "Zinst künftige Zahlungen auf heute ab",
      bestaetigung: "Richtig! Die Kapitalwertmethode ist ein dynamisches Verfahren, das den Zeitpunkt der Zahlungen berücksichtigt.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Bruttomietrendite",
      bedeutung: "Jahresmiete im Verhältnis zum Kaufpreis",
      bestaetigung: "Genau! Die Bruttomietrendite liefert eine erste, grobe Einschätzung eines Objekts.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Eigenkapitalquote",
      bedeutung: "Anteil der eigenen Mittel am Gesamtkapital",
      bestaetigung: "Richtig! Sie ist ein wichtiger Hinweis auf die finanzielle Stabilität.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Leerstandsquote",
      bedeutung: "Anteil der aktuell nicht vermieteten Einheiten",
      bestaetigung: "Genau! Die Leerstandsquote ist das Gegenstück zur Vermietungsquote.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Soll-Ist-Vergleich",
      bedeutung: "Geplante Werte gegen tatsächliche Werte stellen",
      bestaetigung: "Richtig! Bei deutlichen Abweichungen folgt eine Abweichungsanalyse.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Balanced Scorecard",
      bedeutung: "Steuerung mit Finanz-, Kunden-, Prozess- und Lernzielen",
      bestaetigung: "Genau! Die Balanced Scorecard verengt die Steuerung nicht auf reine Finanzkennzahlen.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Risikomatrix",
      bedeutung: "Ordnet Risiken nach Wahrscheinlichkeit und Schaden ein",
      bestaetigung: "Richtig! Aus der Einordnung folgt, ob ein Risiko vermieden, abgesichert, beobachtet oder akzeptiert wird.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Frühwarnsystem",
      bedeutung: "Meldet früh, wenn Kennzahlen aus dem Rahmen laufen",
      bestaetigung: "Genau! So kann das Controlling schon gegensteuern, bevor ein Schaden entsteht.",
    },
    {
      nummer: 21,
      runde: 3,
      begriff: "Organigramm",
      bedeutung: "Zeigt Stellen und Abteilungen eines Unternehmens",
      bestaetigung: "Richtig! Das Organigramm stellt die Aufbauorganisation dar.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Eisenhower-Matrix",
      bedeutung: "Sortiert Aufgaben nach dringend und wichtig",
      bestaetigung: "Genau! Aufgaben werden sofort erledigt, terminiert, delegiert oder gestrichen.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "SMART-Prinzip",
      bedeutung: "Regel für klar formulierte, messbare Ziele",
      bestaetigung: "Richtig! Gute Zielvereinbarungen sind spezifisch, messbar, akzeptiert, realistisch und terminiert.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Mentoring",
      bedeutung: "Erfahrene Kolleginnen und Kollegen begleiten Neue",
      bestaetigung: "Genau! Mentoring gibt Erfahrungswissen weiter und stärkt die Bindung an das Unternehmen.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Coaching",
      bedeutung: "Individuelle Begleitung bei besonderen Aufgaben",
      bestaetigung: "Richtig! Coaching unterstützt einzelne Personen, zum Beispiel angehende Führungskräfte.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Wartung",
      bedeutung: "Bewahrt den Sollzustand einer Anlage",
      bestaetigung: "Genau! Wartung ist eine der vier Grundmaßnahmen der Instandhaltung.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Inspektion",
      bedeutung: "Prüft und beurteilt den Ist-Zustand",
      bestaetigung: "Richtig! Bei der Inspektion wird nur festgestellt und beurteilt, noch nicht repariert.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Instandsetzung",
      bedeutung: "Stellt den Sollzustand nach einem Mangel wieder her",
      bestaetigung: "Genau! Ein Beispiel ist der Austausch einer defekten Pumpe.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Vorausschauende Instandhaltung",
      bedeutung: "Maßnahmen richten sich nach erfassten Zustandsdaten",
      bestaetigung: "Richtig! Sie wird zustandsorientiert ausgelöst, zum Beispiel durch Sensorik oder Verschleißmessung.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "CAFM-System",
      bedeutung: "Software für Anlagen, Wartungstermine und Mängel",
      bestaetigung: "Genau! Ein CAFM-System erfasst technische Anlagen und Termine zentral.",
    },
    {
      nummer: 31,
      runde: 4,
      begriff: "Machbarkeitsstudie",
      bedeutung: "Grobe Prüfung, ob ein Projekt realisierbar ist",
      bestaetigung: "Richtig! Sie ist eine schnelle Einschätzung, ob das Projekt weiterverfolgt wird.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Leistungsverzeichnis",
      bedeutung: "Aufstellung der Bauleistungen in Positionen",
      bestaetigung: "Genau! Es dient als Grundlage für die Ausschreibung.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Ausschreibung",
      bedeutung: "Aufforderung an Firmen, Angebote abzugeben",
      bestaetigung: "Richtig! Danach werden die Angebote verglichen und der Zuschlag erteilt.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Netzplan",
      bedeutung: "Zeigt Vorgänge und ihre Abhängigkeiten als Netz",
      bestaetigung: "Genau! Aus ihm lassen sich Projektdauer und Puffer berechnen.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Kritischer Pfad",
      bedeutung: "Kette von Vorgängen ohne Zeitpuffer",
      bestaetigung: "Richtig! Jede Verzögerung auf dem kritischen Pfad verschiebt das Projektende.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Exposé",
      bedeutung: "Zentrales Verkaufsdokument zu einem Objekt",
      bestaetigung: "Genau! Das Exposé fasst Lage, Ausstattung, Fläche, Preis und Bilder zusammen.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Home Staging",
      bedeutung: "Neutrale Möblierung, damit Räume besser wirken",
      bestaetigung: "Richtig! Home Staging verbessert die Wirkung eines Objekts ohne bauliche Veränderungen.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "CRM-System",
      bedeutung: "Verknüpft Anfragen mit Objekten und Kundendaten",
      bestaetigung: "Genau! Im CRM-System lassen sich Interessenten gezielt über passende Objekte informieren.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Beschwerdemanagement",
      bedeutung: "Klärt Kundenbeschwerden und wertet sie aus",
      bestaetigung: "Richtig! Aus wiederkehrenden Beschwerden lassen sich Prozesse verbessern.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Vergleichswertverfahren",
      bedeutung: "Wert aus Preisen ähnlicher Objekte ableiten",
      bestaetigung: "Genau! Es eignet sich besonders für Standardobjekte wie Eigentumswohnungen mit genug Vergleichsfällen.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Aussagen genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast alle Paare gefunden und wichtige Begriffe der Immobilienwirtschaft wiederholt. Mit „Noch einmal spielen“ bekommst du neue Karten.",
};
