import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Memory-Pool für den Kurs „Geprüfter Technischer Fachwirt".
 * Vier thematische Runden mit je zehn Begriff-Bedeutung-Paaren aus der Kurstheorie (content/technischer-fachwirt/);
 * je Spiel zieht der Server sechs davon. Bewusst ohne Normnummern, Paragrafen und Zahlenwerte. Entwurf, bis zur Fachprüfung gesperrt.
 */
export const memoryTechnik: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Wirtschaft, Rechnungswesen und Recht",
      abschlussmeldung: "Geschafft! Du kannst jetzt Grundbegriffe aus Volkswirtschaft, Rechnungswesen und Recht sicher zuordnen.",
    },
    {
      nummer: 2,
      titel: "Physik, Elektrotechnik und Werkstoffe",
      abschlussmeldung: "Geschafft! Du erkennst jetzt zentrale Begriffe aus Physik, Elektrotechnik, Zeichnen und Werkstoffkunde.",
    },
    {
      nummer: 3,
      titel: "Fertigung, Produktion und Logistik",
      abschlussmeldung: "Geschafft! Du kennst jetzt wichtige Begriffe aus Fertigung, Arbeitsvorbereitung, Produktion und Logistik.",
    },
    {
      nummer: 4,
      titel: "Qualität, Arbeitsschutz und Führung",
      abschlussmeldung: "Geschafft! Du kannst jetzt Begriffe aus Qualitätsmanagement, Arbeitsschutz, Führung und Team richtig zuordnen.",
    },
  ],
  paareProRunde: 6,
  paare: [
    // Runde 1: Wirtschaft, Rechnungswesen und Recht
    {
      nummer: 1,
      runde: 1,
      begriff: "Minimalprinzip",
      bedeutung: "Festes Ziel mit möglichst geringem Mitteleinsatz",
      bestaetigung: "Richtig! Beim Minimalprinzip ist das Ziel fest vorgegeben und der Mitteleinsatz soll möglichst klein sein.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Oligopol",
      bedeutung: "Wenige große Anbieter teilen sich den Markt",
      bestaetigung: "Genau! Im Oligopol beeinflussen sich die wenigen Anbieter mit ihren Preis- und Mengenentscheidungen gegenseitig.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Gleichgewichtspreis",
      bedeutung: "Preis, bei dem Angebot und Nachfrage übereinstimmen",
      bestaetigung: "Richtig! Am Schnittpunkt von Angebots- und Nachfragekurve ist der Markt geräumt.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Kommanditist",
      bedeutung: "Gesellschafter mit auf die Einlage beschränkter Haftung",
      bestaetigung: "Genau! Der Kommanditist haftet nur mit seiner Einlage, führt dafür aber nicht die Geschäfte.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Konzern",
      bedeutung: "Selbstständige Firmen unter einheitlicher Leitung",
      bestaetigung: "Richtig! Im Konzern bleiben die Unternehmen rechtlich selbstständig, werden aber einheitlich geleitet.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Bilanz",
      bedeutung: "Vermögen und Kapital an einem Stichtag gegenübergestellt",
      bestaetigung: "Genau! Aktiva und Passiva einer Bilanz sind immer wertgleich.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Deckungsbeitrag",
      bedeutung: "Erlös abzüglich der variablen Kosten",
      bestaetigung: "Richtig! Der Deckungsbeitrag trägt zur Deckung der Fixkosten und zum Gewinn bei.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Kapitalwert",
      bedeutung: "Auf heute abgezinste Summe aller Ein- und Auszahlungen",
      bestaetigung: "Genau! Ist der Kapitalwert positiv, gilt die Investition als vorteilhaft.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Prokura",
      bedeutung: "Umfassende Vertretungsvollmacht im Handelsgewerbe",
      bestaetigung: "Richtig! Die Prokura ist die weitreichendste handelsrechtliche Vollmacht, die Handlungsvollmacht ist enger.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Eigentumsvorbehalt",
      bedeutung: "Eigentum geht erst mit voller Zahlung über",
      bestaetigung: "Genau! Bis zur vollständigen Zahlung bleibt der Verkäufer Eigentümer der gelieferten Sache.",
    },

    // Runde 2: Physik, Elektrotechnik und Werkstoffe
    {
      nummer: 11,
      runde: 2,
      begriff: "Wirkungsgrad",
      bedeutung: "Verhältnis von Nutzen zu Aufwand bei Energieumwandlung",
      bestaetigung: "Richtig! Wegen der Verluste als Wärme liegt der Wirkungsgrad immer unter dem Idealwert.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Drehmoment",
      bedeutung: "Kraft mal Hebelarm, wirkt auf eine Drehbewegung",
      bestaetigung: "Genau! Das Drehmoment wird in Newtonmeter gemessen.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Ohmsches Gesetz",
      bedeutung: "Verknüpft Spannung, Stromstärke und Widerstand",
      bestaetigung: "Richtig! Mit U = R · I lässt sich eine der drei Größen berechnen, wenn die beiden anderen bekannt sind.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Frequenzumrichter",
      bedeutung: "Stellt die Motordrehzahl stufenlos ein",
      bestaetigung: "Genau! Er verändert Frequenz und Spannung der Motorversorgung elektronisch.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Legierung",
      bedeutung: "Mischung von Metallen zu einem einheitlichen Gefüge",
      bestaetigung: "Richtig! Stahl ist im Kern eine Eisen-Kohlenstoff-Legierung.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Strukturstückliste",
      bedeutung: "Zeigt, welches Teil in welche Baugruppe eingeht",
      bestaetigung: "Genau! Die Strukturstückliste bildet den mehrstufigen Aufbau eines Produkts ab.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Streckgrenze",
      bedeutung: "Ab hier verformt sich ein Werkstoff bleibend",
      bestaetigung: "Richtig! Oberhalb der Streckgrenze verformt sich ein Werkstoff plastisch statt elastisch.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Presspassung",
      bedeutung: "Welle größer als Bohrung, feste Verbindung",
      bestaetigung: "Genau! Eine Presspassung verbindet Teile nach dem Fügen fest und unlösbar, etwa beim Aufpressen einer Lagerbuchse.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Duroplast",
      bedeutung: "Kunststoff, der nach dem Aushärten nicht mehr schmilzt",
      bestaetigung: "Richtig! Duroplaste sind formstabil, aber spröde und nicht durch Umschmelzen wiederverwertbar.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Kerbschlagbiegeversuch",
      bedeutung: "Prüft die Zähigkeit bei schlagartiger Belastung",
      bestaetigung: "Genau! Je mehr Kerbschlagarbeit die Probe aufnimmt, desto zäher ist der Werkstoff.",
    },

    // Runde 3: Fertigung, Produktion und Logistik
    {
      nummer: 21,
      runde: 3,
      begriff: "Urformen",
      bedeutung: "Aus formlosem Stoff entsteht erstmals ein fester Körper",
      bestaetigung: "Richtig! Zum Urformen zählen zum Beispiel Gießen und Sintern.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Autonome Instandhaltung",
      bedeutung: "Bediener übernehmen einfache Wartung und Inspektion",
      bestaetigung: "Genau! Die autonome Instandhaltung ist ein zentraler Baustein von TPM.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "EVA-Prinzip",
      bedeutung: "Eingänge lesen, verarbeiten, Ausgänge ansteuern",
      bestaetigung: "Richtig! So arbeitet eine speicherprogrammierbare Steuerung im ständig wiederholten Zyklus.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Rückwärtsterminierung",
      bedeutung: "Vom Wunschtermin zurückrechnen, wann man starten muss",
      bestaetigung: "Genau! Bei der Rückwärtsterminierung wird vom zugesagten Liefertermin aus geplant.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Arbeitsplan",
      bedeutung: "Legt Arbeitsgänge, Reihenfolge und Betriebsmittel fest",
      bestaetigung: "Richtig! Die Stückliste sagt, woraus ein Produkt besteht, der Arbeitsplan, wie es gefertigt wird.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Rahmenvertrag",
      bedeutung: "Langfristige Grundkonditionen, Menge kommt per Abruf",
      bestaetigung: "Genau! Im Rahmenvertrag stehen Preise und Bedingungen, die konkrete Menge kommt über Lieferabrufe.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Sicherheitsbestand",
      bedeutung: "Puffer gegen Bedarfsschwankungen und Lieferverzug",
      bestaetigung: "Richtig! Der Sicherheitsbestand ergänzt den Meldebestand, bindet aber auch Kapital.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Cross-Docking",
      bedeutung: "Ware wird direkt umgeschlagen statt eingelagert",
      bestaetigung: "Genau! Dadurch sinken Lagerzeiten und Lagerkosten deutlich.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Optimale Losgröße",
      bedeutung: "Rüst- und Lagerkosten je Stück zusammen minimal",
      bestaetigung: "Richtig! Große Lose senken die Rüstkosten je Stück, erhöhen aber die Lagerkosten.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Gesamtanlageneffektivität",
      bedeutung: "Verfügbarkeit mal Leistung mal Qualität",
      bestaetigung: "Genau! Die OEE zeigt auf einen Blick, in welchem der drei Teilfaktoren das größte Verbesserungspotenzial liegt.",
    },

    // Runde 4: Qualität, Arbeitsschutz und Führung
    {
      nummer: 31,
      runde: 4,
      begriff: "Ishikawa-Diagramm",
      bedeutung: "Ursache-Wirkungs-Diagramm in Fischgrätenform",
      bestaetigung: "Richtig! Es ordnet mögliche Fehlerursachen den Kategorien Mensch, Maschine, Material, Methode, Milieu und Management zu.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "FMEA",
      bedeutung: "Bewertet mögliche Fehler schon vor der Serienfertigung",
      bestaetigung: "Genau! Die FMEA setzt vorbeugend an, weil spätere Korrekturen in der Serie teurer wären.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Abfallhierarchie",
      bedeutung: "Rangfolge: erst vermeiden, zuletzt beseitigen",
      bestaetigung: "Richtig! Vermeidung steht an erster Stelle, weil nicht entstandener Abfall keine Entsorgungskosten verursacht.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "TOP-Prinzip",
      bedeutung: "Erst technisch, dann organisatorisch, dann persönlich",
      bestaetigung: "Genau! Persönliche Schutzausrüstung kommt erst zuletzt, weil sie die Gefahr nicht beseitigt.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Gefährdungsbeurteilung",
      bedeutung: "Systematische Ermittlung und Bewertung von Gefahren",
      bestaetigung: "Richtig! Sie muss bei wesentlichen Änderungen, etwa einer neuen Maschine, aktualisiert werden.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Storming-Phase",
      bedeutung: "Teamphase, in der Konflikte offen aufbrechen",
      bestaetigung: "Genau! Die Storming-Phase ist ein normaler Entwicklungsschritt und kein Scheitern des Teams.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Vier-Ohren-Modell",
      bedeutung: "Sachinhalt, Selbstoffenbarung, Beziehung und Appell",
      bestaetigung: "Richtig! Jede Nachricht enthält diese vier Ebenen gleichzeitig, deshalb entstehen leicht Missverständnisse.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Hygienefaktoren",
      bedeutung: "Verhindern Unzufriedenheit, motivieren aber nicht",
      bestaetigung: "Genau! Bezahlung und Arbeitsbedingungen zählen dazu, echte Motivation entsteht eher durch Motivatoren.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Management by Objectives",
      bedeutung: "Führen durch gemeinsam vereinbarte Ziele",
      bestaetigung: "Richtig! Die Ziele sind überprüfbar, den Weg dorthin bestimmen die Mitarbeitenden selbst.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Cash Cows",
      bedeutung: "Hoher Marktanteil, wenig Wachstum, stabile Überschüsse",
      bestaetigung: "Genau! In der BCG-Matrix finanzieren sie die Entwicklung der Stars und aussichtsreicher Question Marks.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus dem ganzen Technischen Fachwirt zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten und eine andere Mischung.",
};
