import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit): Memory-Pool für den Kurs „Geprüfter Fachwirt für Gesundheits- und Sozialwesen".
 * Vier thematische Runden mit je zehn Begriff-Bedeutung-Paaren; pro Spiel werden je Runde sechs Paare gezogen.
 * Alle Inhalte stammen aus den Theorietexten und Karteikarten unter content/fachwirt-gesundheit-soziales/
 * (Rechtsstand dort: 29.09.2026). Bewusst keine Rechtsdetails: keine Paragrafen, Zahlenwerte, Fristen,
 * Beitragssätze oder Leistungsansprüche. Entwurf — vor Verwendung durch echte Lernende fachlich prüfen.
 */
export const memoryGesundheitSoziales: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Ziele, Organisation und Marketing",
      abschlussmeldung: "Geschafft! Du kennst jetzt zentrale Begriffe zu Zielen, Organisation, Veränderung und Marketing.",
    },
    {
      nummer: 2,
      titel: "Qualität, Risiko und Zeit",
      abschlussmeldung: "Geschafft! Du kannst Qualitätsdimensionen, Audits, Risiken und Zeitmanagement-Methoden auseinanderhalten.",
    },
    {
      nummer: 3,
      titel: "Team, Projekte und Personal",
      abschlussmeldung: "Geschafft! Du erkennst jetzt Begriffe aus Kommunikation, Projektarbeit, Führung und Personalentwicklung.",
    },
    {
      nummer: 4,
      titel: "Finanzierung, Kosten und Kennzahlen",
      abschlussmeldung: "Geschafft! Du ordnest Begriffe aus Rechnungswesen, Finanzierung und Kostenrechnung sicher zu.",
    },
  ],
  paareProRunde: 6,
  paare: [
    // Runde 1: Ziele, Organisation und Marketing
    {
      nummer: 1,
      runde: 1,
      begriff: "Leitbild",
      bedeutung: "Zweck und Werte einer Organisation, Basis der Ziele",
      bestaetigung: "Richtig! Aus dem Leitbild werden strategische und operative Ziele abgeleitet.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "SWOT-Analyse",
      bedeutung: "Stärken, Schwächen, Chancen und Risiken im Überblick",
      bestaetigung: "Genau! Stärken und Schwächen sind intern, Chancen und Risiken kommen von außen.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Operatives Ziel",
      bedeutung: "Kurzfristig, konkret und messbar",
      bestaetigung: "Richtig! Operative Ziele leiten sich aus den strategischen Zielen ab.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Stabsstelle",
      bedeutung: "Berät die Leitung, ohne Weisungen zu erteilen",
      bestaetigung: "Genau! Stabsstellen unterstützen fachlich, haben aber keine Weisungsbefugnis.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Organigramm",
      bedeutung: "Grafik der Stellen und ihrer Über- und Unterordnung",
      bestaetigung: "Richtig! Das Organigramm stellt die Aufbauorganisation grafisch dar.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Verdeckter Widerstand",
      bedeutung: "Dienst nach Vorschrift statt offenem Widerspruch",
      bestaetigung: "Genau! Verdeckter Widerstand zeigt sich indirekt, etwa durch das Ignorieren neuer Vorgaben.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Marktsegmentierung",
      bedeutung: "Gesamtmarkt in ähnliche Teilgruppen einteilen",
      bestaetigung: "Richtig! Segmente erlauben eine passgenaue Ansprache der Zielgruppen.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Marktbeobachtung",
      bedeutung: "Dauerhaftes Verfolgen der Marktentwicklung",
      bestaetigung: "Genau! Marktbeobachtung ist auf Dauer angelegt, zum Beispiel beim Blick auf neue Wettbewerber.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Öffentlichkeitsarbeit",
      bedeutung: "Schafft Vertrauen und Bekanntheit, nicht direkt Absatz",
      bestaetigung: "Richtig! Gerade im Sozialwesen wirkt sie oft glaubwürdiger als klassische Werbung.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Diversifikation",
      bedeutung: "Neues Angebot für einen neuen Markt",
      bestaetigung: "Genau! Diversifikation gilt als die risikoreichste der vier Wachstumsstrategien.",
    },
    // Runde 2: Qualität, Risiko und Zeit
    {
      nummer: 11,
      runde: 2,
      begriff: "Strukturqualität",
      bedeutung: "Rahmenbedingungen wie Personal und Ausstattung",
      bestaetigung: "Richtig! Zur Strukturqualität zählt auch der Arbeits- und Gesundheitsschutz.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Prozessqualität",
      bedeutung: "Wie eine Leistung tatsächlich erbracht wird",
      bestaetigung: "Genau! Dazu gehört die Einhaltung von Standards während des Einsatzes.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Ergebnisqualität",
      bedeutung: "Das tatsächlich erzielte Resultat einer Leistung",
      bestaetigung: "Richtig! Gemessen wird sie zum Beispiel an der Zufriedenheit der betreuten Menschen.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "PDCA-Zyklus",
      bedeutung: "Planen, Umsetzen, Überprüfen, Anpassen",
      bestaetigung: "Genau! Der Kreislauf wiederholt sich und verbessert Prozesse fortlaufend.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Internes Audit",
      bedeutung: "Prüfung durch die Organisation selbst",
      bestaetigung: "Richtig! Ein Zertifizierungsaudit dagegen führt eine unabhängige Stelle durch.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Qualitätsindikator",
      bedeutung: "Messbares Merkmal, das auf die Güte hinweist",
      bestaetigung: "Genau! Ein einzelner Indikator ist nur ein Ausgangspunkt für weitere Analysen.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Beschwerdemanagement",
      bedeutung: "Nimmt Unzufriedenheit auf und lernt daraus",
      bestaetigung: "Richtig! Es soll Zufriedenheit wiederherstellen und Schwachstellen sichtbar machen.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Risikomatrix",
      bedeutung: "Ordnet Risiken nach Wahrscheinlichkeit und Schaden",
      bestaetigung: "Genau! So lassen sich Risiken sichtbar machen und vergleichen.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Eisenhower-Prinzip",
      bedeutung: "Aufgaben nach wichtig und dringend sortieren",
      bestaetigung: "Richtig! Wichtige und dringende Aufgaben werden sofort erledigt.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Zeitdieb",
      bedeutung: "Bindet Arbeitszeit unproduktiv, z. B. Unterbrechungen",
      bestaetigung: "Genau! Mit Selbstbeobachtung lassen sich eigene Zeitdiebe erkennen.",
    },
    // Runde 3: Team, Projekte und Personal
    {
      nummer: 21,
      runde: 3,
      begriff: "Schnittstelle",
      bedeutung: "Übergabepunkt zwischen zwei Bereichen",
      bestaetigung: "Richtig! An Schnittstellen wechseln Informationen oder Zuständigkeiten.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Vier-Seiten-Modell",
      bedeutung: "Sachinhalt, Selbstoffenbarung, Beziehung, Appell",
      bestaetigung: "Genau! Dieselbe Aussage kann auf diesen Ebenen unterschiedlich verstanden werden.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "Storming",
      bedeutung: "Teamphase mit ersten offenen Konflikten",
      bestaetigung: "Richtig! Danach folgen Norming und Performing.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Lenkungsausschuss",
      bedeutung: "Entscheidet grundsätzlich und überwacht ein Projekt",
      bestaetigung: "Genau! Das Projektteam dagegen arbeitet operativ an den Inhalten.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Meilenstein",
      bedeutung: "Wichtiges, terminiertes Zwischenergebnis im Projekt",
      bestaetigung: "Richtig! Meilensteine machen den Projektfortschritt überprüfbar.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Stellenbeschreibung",
      bedeutung: "Hält Aufgaben und Anforderungen einer Position fest",
      bestaetigung: "Genau! Sie dient als Grundlage für Ausschreibung, Auswahl und Beurteilung.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Vier-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen, Üben",
      bestaetigung: "Richtig! Mit dieser Methode lassen sich praktische Fertigkeiten Schritt für Schritt vermitteln.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Hygienefaktor",
      bedeutung: "Verhindert Unzufriedenheit, motiviert aber nicht allein",
      bestaetigung: "Genau! Motivatoren wie Anerkennung und Verantwortung wirken dagegen echt motivierend.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Mediation",
      bedeutung: "Konfliktklärung mit neutraler dritter Person",
      bestaetigung: "Richtig! Die Beteiligten finden die Lösung dabei selbst.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Mentoring",
      bedeutung: "Erfahrene Fachkraft begleitet Neue eher informell",
      bestaetigung: "Genau! Coaching ist dagegen meist eine professionelle Einzelbegleitung.",
    },
    // Runde 4: Finanzierung, Kosten und Kennzahlen
    {
      nummer: 31,
      runde: 4,
      begriff: "Bilanz",
      bedeutung: "Mittelherkunft und Mittelverwendung zum Stichtag",
      bestaetigung: "Richtig! Die Summe der Aktiva entspricht stets der Summe der Passiva.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Inventur",
      bedeutung: "Bestandsaufnahme aller Vermögen und Schulden",
      bestaetigung: "Genau! Das daraus entstehende Verzeichnis heißt Inventar.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Gewinn- und Verlustrechnung",
      bedeutung: "Erträge und Aufwendungen einer Periode im Vergleich",
      bestaetigung: "Richtig! Anders als die Bilanz bildet die GuV einen Zeitraum ab, nicht einen Stichtag.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Sachleistungsprinzip",
      bedeutung: "Behandlung ohne Vorleistung der Versicherten",
      bestaetigung: "Genau! Die Kasse rechnet unmittelbar mit den Leistungserbringern ab.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Solidaritätsprinzip",
      bedeutung: "Beitrag richtet sich nach Einkommen, nicht nach Risiko",
      bestaetigung: "Richtig! Dieses Grundprinzip prägt die gesetzliche Krankenversicherung.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Nachrang der Sozialhilfe",
      bedeutung: "Sie greift erst, wenn andere Mittel nicht reichen",
      bestaetigung: "Genau! Vorrangig sind eigenes Einkommen und andere Sicherungssysteme.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Fixe Kosten",
      bedeutung: "Bleiben unabhängig von der Leistungsmenge gleich",
      bestaetigung: "Richtig! Ein Beispiel ist die Miete der Geschäftsstelle.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Deckungsbeitrag",
      bedeutung: "Erlös abzüglich der variablen Kosten einer Leistung",
      bestaetigung: "Genau! Er trägt zunächst zur Deckung der fixen Kosten bei.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Break-even-Punkt",
      bedeutung: "Ab hier decken die Beiträge alle fixen Kosten",
      bestaetigung: "Richtig! Er wird auch Gewinnschwelle genannt.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Liquiditätsplanung",
      bedeutung: "Sichert, dass Zahlungen jederzeit möglich sind",
      bestaetigung: "Genau! Das ist wichtig, wenn Zahlungseingänge verzögert kommen, Kosten aber laufend anfallen.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus allen Bereichen des Fachwirt-Kurses zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten — spiel gern noch eine Runde!",
};
