import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Paar-Pool für das Memory „Transport und Logistik" (Kurs Transport Management and Logistics,
 * Fiktivfirma Fracora). Vier Themenrunden mit je zehn Paaren; pro Spiel werden je Runde sechs Paare gezogen. Alles stammt aus der
 * Kurstheorie (content/transport-management-logistics), bewusst ohne Rechts- und Betragsdetails. Entwurf, bis zur Fachprüfung gesperrt.
 */
export const memoryLogistik: MemoryPayload = {
  paareProRunde: 6,
  runden: [
    {
      nummer: 1,
      titel: "Markt, Vertrieb und Kalkulation",
      abschlussmeldung: "Geschafft! Du kennst jetzt wichtige Begriffe aus Marktanalyse, Vertrieb und Kalkulation. Mit „Noch einmal spielen“ bekommst du neue Karten.",
    },
    {
      nummer: 2,
      titel: "Leistungen, Verträge und Digitalisierung",
      abschlussmeldung: "Geschafft! Du erkennst jetzt Begriffe zu Leistungsentwicklung, Frachtpapieren und digitalen Systemen. Mit „Noch einmal spielen“ kommen neue Karten.",
    },
    {
      nummer: 3,
      titel: "Transport, Lager und Verkehrsträger",
      abschlussmeldung: "Geschafft! Du kannst jetzt Begriffe aus Tourenplanung, Lager und Ladungssicherung zuordnen. Mit „Noch einmal spielen“ gibt es neue Karten.",
    },
    {
      nummer: 4,
      titel: "Führung, Team und Ausbildung",
      abschlussmeldung: "Geschafft! Du kennst jetzt zentrale Begriffe zu Führung, Kommunikation, Teamarbeit und Ausbildung. Mit „Noch einmal spielen“ wechseln die Karten.",
    },
  ],
  paare: [
    // Runde 1: Markt, Vertrieb und Kalkulation
    {
      nummer: 1,
      runde: 1,
      begriff: "Marktvolumen",
      bedeutung: "Tatsächlicher Umsatz aller Anbieter im Teilmarkt",
      bestaetigung: "Richtig! Das Marktvolumen ist der Wert, den alle Anbieter in einem Teilmarkt tatsächlich erzielen.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Marktpotenzial",
      bedeutung: "Theoretisch größtmögliche Nachfrage",
      bestaetigung: "Genau! Das Marktpotenzial ist die Obergrenze, wenn alle möglichen Auftraggeber die Leistung nutzen würden.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Marktanteil",
      bedeutung: "Eigener Umsatzanteil am gesamten Teilmarkt",
      bestaetigung: "Richtig! Der Marktanteil setzt den eigenen Umsatz ins Verhältnis zum Marktvolumen.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Primärforschung",
      bedeutung: "Selbst erhobene, neue Daten für einen Zweck",
      bestaetigung: "Genau! Eine eigene Kundenbefragung ist ein typisches Beispiel für Primärforschung.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Sekundärforschung",
      bedeutung: "Auswertung bereits vorhandener Daten",
      bestaetigung: "Richtig! Sekundärforschung nutzt vorhandene Quellen und ist meist günstiger und schneller.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Shipper",
      bedeutung: "Verladendes Unternehmen als Auftraggeber",
      bestaetigung: "Genau! Ein Shipper fragt Transport- oder Logistikleistungen nach.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Benchmarking",
      bedeutung: "Vergleich eigener Kennzahlen mit den Besten",
      bestaetigung: "Richtig! Beim Benchmarking misst sich ein Unternehmen systematisch an Wettbewerbern oder dem Branchendurchschnitt.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Hub-and-Spoke-System",
      bedeutung: "Sendungen werden zentral gebündelt und verteilt",
      bestaetigung: "Genau! Das senkt die Kosten je Sendung, kann aber die Transportzeit einzelner Sendungen verlängern.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Fixkosten",
      bedeutung: "Kosten, die unabhängig von der Menge anfallen",
      bestaetigung: "Richtig! Zu den Fixkosten zählen zum Beispiel Abschreibungen auf Lkw.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Variable Kosten",
      bedeutung: "Kosten, die mit der Leistungsmenge steigen",
      bestaetigung: "Genau! Kraftstoff und Maut je gefahrenem Kilometer sind typische variable Kosten.",
    },
    // Runde 2: Leistungen, Verträge und Digitalisierung
    {
      nummer: 11,
      runde: 2,
      begriff: "Uno-actu-Prinzip",
      bedeutung: "Leistung und Nutzung geschehen zeitgleich",
      bestaetigung: "Richtig! Ein Transport entsteht genau in dem Moment, in dem er stattfindet, und lässt sich nicht auf Vorrat erbringen.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Immaterialität",
      bedeutung: "Leistung ist nicht anfassbar und nicht lagerbar",
      bestaetigung: "Genau! Eine Dienstleistung lässt sich nicht wie eine Ware einlagern und später verkaufen.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Modularisierung",
      bedeutung: "Standardkern plus frei wählbare Zusatzmodule",
      bestaetigung: "Richtig! So können Kunden zum Beispiel Kommissionierung oder Verpackung nach Bedarf hinzubuchen.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Ansoff-Matrix",
      bedeutung: "Vier Wachstumsstrategien nach Markt und Leistung",
      bestaetigung: "Genau! Dazu gehören Marktdurchdringung, Marktentwicklung, Produktentwicklung und Diversifikation.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "PDCA-Zyklus",
      bedeutung: "Planen, Umsetzen, Prüfen, Verbessern im Kreislauf",
      bestaetigung: "Richtig! Der PDCA-Zyklus sorgt für eine laufende, systematische Verbesserung.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Service Level Agreement",
      bedeutung: "Vertraglich festgelegte, messbare Qualitätsziele",
      bestaetigung: "Genau! Ein SLA macht Leistungsversprechen wie Pünktlichkeit überprüfbar.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Frachtbrief",
      bedeutung: "Nachweis über Vertrag und Übernahme des Gutes",
      bestaetigung: "Richtig! Der Frachtbrief dokumentiert den Vertrag und bestätigt, dass das Gut übernommen wurde.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Track & Trace",
      bedeutung: "Sendungsstatus entlang der Transportkette erfassen",
      bestaetigung: "Genau! Kunden sehen so jederzeit, wo ihre Sendung gerade ist.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "EDI",
      bedeutung: "Automatischer Austausch von Geschäftsdokumenten",
      bestaetigung: "Richtig! Mit EDI entfällt die manuelle Neuerfassung von Daten.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "TMS",
      bedeutung: "Software für Planung und Kontrolle von Transporten",
      bestaetigung: "Genau! Ein Transportmanagementsystem unterstützt unter anderem die Tourenplanung.",
    },
    // Runde 3: Transport, Lager und Verkehrsträger
    {
      nummer: 21,
      runde: 3,
      begriff: "Tourenplanung",
      bedeutung: "Route und Reihenfolge mehrerer Stopps festlegen",
      bestaetigung: "Richtig! Ziel ist es, Strecke und Fahrzeit zu verkürzen und dabei alle Vorgaben einzuhalten.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Disposition",
      bedeutung: "Fahrzeuge und Fahrpersonal den Touren zuweisen",
      bestaetigung: "Genau! Die Disposition ordnet den geplanten Touren die passenden Ressourcen zu.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "Leerkilometer",
      bedeutung: "Gefahrene Strecke ohne Ladung",
      bestaetigung: "Richtig! Viele Leerkilometer verursachen Kosten, ohne Erlös zu bringen.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Formschluss",
      bedeutung: "Ladung liegt lückenlos an und kann nicht rutschen",
      bestaetigung: "Genau! Die Ladung liegt an Wänden oder Sperrbalken an und kann sich nicht bewegen.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Blocklager",
      bedeutung: "Waren werden ohne Regal direkt gestapelt",
      bestaetigung: "Richtig! Das spart Platz, schränkt aber den Direktzugriff auf einzelne Artikel ein.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Kommissionierung",
      bedeutung: "Waren für einen Kundenauftrag zusammenstellen",
      bestaetigung: "Genau! Aus dem Gesamtsortiment werden die passenden Artikel und Mengen zusammengestellt.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "ABC-Analyse",
      bedeutung: "Artikel nach ihrem Wertanteil einteilen",
      bestaetigung: "Richtig! A-Artikel haben einen großen Umsatzanteil bei wenigen Artikeln.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Sicherheitsbestand",
      bedeutung: "Zusätzlicher Puffer gegen Schwankungen",
      bestaetigung: "Genau! Er fängt Schwankungen bei Verbrauch oder Lieferzeit ab und beugt Engpässen vor.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Kombinierter Verkehr",
      bedeutung: "Mehrere Verkehrsträger, nur die Ladeeinheit wechselt",
      bestaetigung: "Richtig! Am Terminal wird die ganze Ladeeinheit umgeschlagen, nicht das einzelne Gut.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Modal Shift",
      bedeutung: "Verlagerung der Fracht von der Straße auf Schiene",
      bestaetigung: "Genau! Das senkt bei planbaren Großmengen den CO2-Ausstoß.",
    },
    // Runde 4: Führung, Team und Ausbildung
    {
      nummer: 31,
      runde: 4,
      begriff: "Autoritärer Führungsstil",
      bedeutung: "Die Führungskraft entscheidet allein",
      bestaetigung: "Richtig! Das passt zum Beispiel, wenn im Lager sofort eine Anweisung nötig ist.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Management by Exception",
      bedeutung: "Eingreifen nur bei Abweichungen",
      bestaetigung: "Genau! Innerhalb festgelegter Toleranzgrenzen handeln die Mitarbeitenden selbstständig.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Hygienefaktoren",
      bedeutung: "Verhindern Unzufriedenheit, motivieren aber nicht",
      bestaetigung: "Richtig! Echte Motivation entsteht nach Herzberg erst durch Motivatoren wie Verantwortung.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Eisenhower-Matrix",
      bedeutung: "Aufgaben nach Wichtigkeit und Dringlichkeit ordnen",
      bestaetigung: "Genau! So bleiben wichtige, aber nicht dringende Aufgaben nicht dauerhaft liegen.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Vier-Seiten-Modell",
      bedeutung: "Jede Nachricht sendet mehrere Botschaften zugleich",
      bestaetigung: "Richtig! Neben der Sache enthalten Nachrichten auch Selbstoffenbarung, Beziehungshinweis und Appell.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Aktives Zuhören",
      bedeutung: "Nachfragen und Zusammenfassen sichert Verständnis",
      bestaetigung: "Genau! Das zeigt Wertschätzung und beugt Missverständnissen vor.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Storming-Phase",
      bedeutung: "Teamphase mit ersten Meinungsverschiedenheiten",
      bestaetigung: "Richtig! Diese Phase gehört zur normalen Teamentwicklung.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Win-win-Strategie",
      bedeutung: "Beide Seiten erarbeiten gemeinsam eine Lösung",
      bestaetigung: "Genau! Sie gilt langfristig meist als der erfolgversprechendste Weg, einen Konflikt zu lösen.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Mediation",
      bedeutung: "Neutrale Person moderiert das Konfliktgespräch",
      bestaetigung: "Richtig! Die Lösung erarbeiten die Konfliktparteien selbst.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Vier-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen, Üben lassen",
      bestaetigung: "Genau! So lernen Auszubildende praktische Fertigkeiten Schritt für Schritt.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus allen Bereichen von Transport und Logistik zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten.",
};
