import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, Nutzer-Vorgabe vom 06.10.2026): Paar-Pool „Versicherungen und Finanzanlagen" für das Memory.
 * Vier Themenrunden (je ein Fachgebiet des Kurses) mit je zehn Paaren im Pool; jede Runde zeigt bei jedem Spiel sechs davon.
 * Bewusst ohne Rechtsdetails (keine Paragrafen, Zahlen, Fristen, Steuer- oder Beratungsrechtsregeln) und ohne Produktempfehlungen.
 * Inhalt bleibt bis zur Fachprüfung gesperrt.
 */
export const memoryVersicherung: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Vorsorge: Kranken, Pflege, Unfall und Rente",
      abschlussmeldung: "Geschafft! Du kennst wichtige Begriffe rund um Gesundheit, Pflege, Unfall und Altersvorsorge.",
    },
    {
      nummer: 2,
      titel: "Gewerbekunden: Sach, Haftpflicht und Risiko",
      abschlussmeldung: "Geschafft! Du kannst Begriffe aus Sach-, Haftpflicht- und Betriebsunterbrechungsschutz sicher zuordnen.",
    },
    {
      nummer: 3,
      titel: "Produkt, Kunde, Schaden und Leistung",
      abschlussmeldung: "Geschafft! Du erkennst Begriffe aus Produktentwicklung, Beratung, Schaden- und Leistungsbearbeitung.",
    },
    {
      nummer: 4,
      titel: "Steuerung, Führung, Projekt und Ausbildung",
      abschlussmeldung: "Geschafft! Du kennst Begriffe aus Controlling, Führung, Projektmanagement und Berufsausbildung.",
    },
  ],
  paareProRunde: 6,
  paare: [
    // ---- Runde 1: Vorsorge ----
    {
      nummer: 1,
      runde: 1,
      begriff: "Äquivalenzprinzip",
      bedeutung: "Beitrag richtet sich nach dem eigenen Risiko",
      bestaetigung: "Richtig! In der privaten Krankenversicherung zählt das individuelle Risiko, nicht das Einkommen.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Krankentagegeld",
      bedeutung: "Ersetzt bei langer Krankheit den Verdienstausfall",
      bestaetigung: "Genau! Besonders für Selbstständige ist der Ausgleich bei längerer Arbeitsunfähigkeit wichtig.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Alterungsrückstellung",
      bedeutung: "Früh angespartes Polster für spätere höhere Kosten",
      bestaetigung: "Richtig! Sie soll starke Beitragssprünge im Alter abfedern.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Pflegelücke",
      bedeutung: "Unterschied zwischen tatsächlichen Kosten und Leistung",
      bestaetigung: "Genau! Die gesetzliche Pflegeversicherung ist als Teilkaskoversicherung angelegt.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Pflegegeld",
      bedeutung: "Zahlung, wenn Angehörige die Hilfe zu Hause leisten",
      bestaetigung: "Richtig! Bei Pflege durch nahestehende Personen gibt es eine Geldleistung statt Sachleistung.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Invaliditätsleistung",
      bedeutung: "Einmalzahlung nach Unfall mit bleibenden Folgen",
      bestaetigung: "Genau! Sie ist die zentrale Leistung der privaten Unfallversicherung.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Berufsunfähigkeit",
      bedeutung: "Der zuletzt ausgeübte Beruf geht dauerhaft nicht mehr",
      bestaetigung: "Richtig! Die Berufsunfähigkeitsversicherung stellt auf den konkreten, zuletzt ausgeübten Beruf ab.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Grundfähigkeiten",
      bedeutung: "Zahlt bei Verlust von Fähigkeiten wie Sehen oder Hören",
      bestaetigung: "Genau! Bei dieser Absicherung zählen im Vertrag benannte Fähigkeiten statt des Berufs.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Drei-Schichten-Modell",
      bedeutung: "Ordnet Vorsorgeformen in drei Gruppen",
      bestaetigung: "Richtig! Das Modell hilft, Altersvorsorgeprodukte einzuordnen.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Betriebliche Altersversorgung",
      bedeutung: "Vorsorge für das Alter, die über den Arbeitgeber läuft",
      bestaetigung: "Genau! Sie wird auch kurz bAV genannt und kann auf verschiedenen Wegen umgesetzt werden.",
    },
    // ---- Runde 2: Gewerbekunden ----
    {
      nummer: 11,
      runde: 2,
      begriff: "Einbruchdiebstahl",
      bedeutung: "Schaden mit nachweisbaren Spuren des Eindringens",
      bestaetigung: "Richtig! Ohne Einbruchspuren greift dieser Schutz in der Regel nicht.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Elementarschäden",
      bedeutung: "Naturgefahren wie Überschwemmung oder Erdrutsch",
      bestaetigung: "Genau! Sie müssen meist als eigener Baustein zusätzlich eingeschlossen werden.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Betriebshaftpflicht",
      bedeutung: "Schützt vor Ansprüchen Dritter aus der Betriebstätigkeit",
      bestaetigung: "Richtig! Sie deckt Personen- und Sachschäden Dritter sowie daraus folgende Vermögensschäden.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Produkthaftpflicht",
      bedeutung: "Greift bei Schäden durch ein fehlerhaftes Produkt",
      bestaetigung: "Genau! Sie ist oft Teil der Betriebshaftpflicht oder wird ergänzend abgeschlossen.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Echter Vermögensschaden",
      bedeutung: "Geldverlust ohne Personen- oder Sachschaden",
      bestaetigung: "Richtig! Dafür braucht es eine eigene Vermögensschadenhaftpflicht, etwa bei fehlerhafter Beratung.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "D&O-Versicherung",
      bedeutung: "Schützt Führungskräfte bei Pflichtverletzungen im Amt",
      bestaetigung: "Genau! Sie sichert Mitglieder der Geschäftsleitung gegen persönliche Inanspruchnahme ab.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Cyberversicherung",
      bedeutung: "Deckt Eigen- und Drittschäden nach einem IT-Vorfall",
      bestaetigung: "Richtig! Vor dem Abschluss wird meist ein Risikofragebogen zur IT-Sicherheit ausgefüllt.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Betriebsunterbrechung",
      bedeutung: "Ersetzt den Ertragsausfall nach einem Sachschaden",
      bestaetigung: "Genau! Sie ist eine Folgeversicherung zur Sachversicherung.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Unterversicherung",
      bedeutung: "Summe zu niedrig, Ersatz fällt anteilig geringer aus",
      bestaetigung: "Richtig! Eine sorgfältige Ermittlung der Versicherungssumme beugt dem vor.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Überwälzen",
      bedeutung: "Folgen auf Dritte übertragen, etwa per Versicherung",
      bestaetigung: "Genau! Eine Versicherung verlagert nur die finanziellen Folgen und ersetzt keine Schadenverhütung.",
    },
    // ---- Runde 3: Produkt, Kunde, Schaden und Leistung ----
    {
      nummer: 21,
      runde: 3,
      begriff: "Nettoprämie",
      bedeutung: "Deckt die erwarteten Leistungen, ohne Zuschläge",
      bestaetigung: "Richtig! Dazu kommen später noch Kosten und ein Sicherheitszuschlag.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Aktuariat",
      bedeutung: "Berechnet Prämien und überwacht die Schadenreserven",
      bestaetigung: "Genau! Es ist für die versicherungsmathematische Kalkulation zuständig.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "Rückversicherung",
      bedeutung: "Der Versicherer gibt Großrisiken an Partner ab",
      bestaetigung: "Richtig! So werden Großschadenspitzen abgefedert.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Produktlebenszyklus",
      bedeutung: "Einführung, Wachstum, Reife, Sättigung, Rückgang",
      bestaetigung: "Genau! Das Produktmanagement steuert ein Produkt durch diese Phasen.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Bedarfsanalyse",
      bedeutung: "Erhebt, was die Kundschaft absichern muss",
      bestaetigung: "Richtig! Sie steht am Anfang jeder Beratung.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Cross-Selling",
      bedeutung: "Verkauf ergänzender Produkte an Bestandskundschaft",
      bestaetigung: "Genau! Es muss sich weiterhin an den Bedürfnissen der Kundschaft orientieren.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Schadenmeldung",
      bedeutung: "Erste Mitteilung eines Ereignisses an den Versicherer",
      bestaetigung: "Richtig! Sie startet den Schadenprozess, zum Beispiel per Hotline oder Kundenportal.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Regress",
      bedeutung: "Rückforderung gezahlter Entschädigung beim Verursacher",
      bestaetigung: "Genau! Er wirkt auch vorbeugend, weil Verursacher wirtschaftlich zur Sorgfalt angehalten werden.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Leistungsprüfung",
      bedeutung: "Prüft Vertrag, Wartezeit und Ausschlüsse vor der Zahlung",
      bestaetigung: "Richtig! Erst danach folgt die Entscheidung über den Leistungsfall.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Betrugsprävention",
      bedeutung: "Auffälligkeiten erkennen, ohne Ehrliche auszubremsen",
      bestaetigung: "Genau! Ehrliche Kundschaft darf nicht unnötig verzögert werden.",
    },
    // ---- Runde 4: Steuerung, Führung, Projekt, Ausbildung ----
    {
      nummer: 31,
      runde: 4,
      begriff: "Balanced Scorecard",
      bedeutung: "Steuerung mit vier gleichrangigen Perspektiven",
      bestaetigung: "Richtig! Sie ergänzt rückblickende Finanzzahlen um weitere Blickwinkel.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Combined Ratio",
      bedeutung: "Summe aus Schadenquote und Kostenquote",
      bestaetigung: "Genau! Je niedriger sie ausfällt, desto besser arbeitet die Sparte im Versicherungsgeschäft.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Plan-Ist-Vergleich",
      bedeutung: "Geplante und erreichte Werte nebeneinander",
      bestaetigung: "Richtig! Danach folgt die Analyse der Abweichungen.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Situatives Führen",
      bedeutung: "Der Führungsstil richtet sich nach dem Reifegrad",
      bestaetigung: "Genau! Neue Mitarbeitende brauchen oft engere Anleitung als erfahrene.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Management by Objectives",
      bedeutung: "Führen durch Zielvereinbarung",
      bestaetigung: "Richtig! Das Ziel wird gemeinsam festgelegt, der Weg bleibt offen.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "SMART-Ziel",
      bedeutung: "Spezifisch, messbar, attraktiv, realistisch, terminiert",
      bestaetigung: "Genau! „Mehr Neugeschäft machen“ wäre dagegen kein SMARTes Ziel.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Kritischer Pfad",
      bedeutung: "Vorgänge ohne Puffer: Verzögerung verschiebt das Ende",
      bestaetigung: "Richtig! Jede Verspätung auf diesem Pfad verlängert das Projekt.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Lessons Learned",
      bedeutung: "Erkenntnisse aus dem Projekt für künftige Vorhaben",
      bestaetigung: "Genau! Sie werden nach dem Projektabschluss dokumentiert.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Vier-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen, Üben lassen",
      bestaetigung: "Richtig! Sie eignet sich für handlungsorientiertes Anlernen.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Berichtsheft",
      bedeutung: "Nachweis der vermittelten Ausbildungsinhalte",
      bestaetigung: "Genau! Es dient zugleich als Kontrollinstrument für die Ausbildung.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Aussagen genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus allen vier Fachgebieten zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten — spiel gern noch eine Runde!",
};
