import type { KreuzwortraetselPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Wortpool für das Kreuzworträtsel „Transport und Logistik" (Kurs Transport Management and
 * Logistics, Fiktivfirma Fracora). 33 kurze, alltagsnahe Begriffe aus den drei Handlungsbereichen; der Server zieht je Start zehn
 * Wörter und legt das Gitter selbst an (keine Positionen im Inhalt). Alles stammt aus der Kurstheorie (content/transport-management-logistics);
 * bewusst ohne Rechts- und Betragsdetails (Haftung, Lenkzeiten, Gefahrgut, Zoll nur als allgemeine Begriffe). Entwurf, bis zur Fachprüfung gesperrt.
 */
export const kreuzwortraetselLogistik: KreuzwortraetselPayload = {
  wortzahl: 10,
  woerter: [
    // Handlungsbereich 1: Markt, Leistungen, Vertrieb, Digitalisierung
    {
      nummer: 1,
      hinweis: "Verladendes Unternehmen, das Transporte als Auftraggeber bestellt.",
      tipp: "Englisches Wort mit sieben Buchstaben, beginnt mit S.",
      loesung: "SHIPPER",
      bestaetigung: "Genau! Ein Shipper ist das verladende Unternehmen, das Transport- oder Logistikleistungen in Auftrag gibt.",
    },
    {
      nummer: 2,
      hinweis: "Eigener Umsatz im Verhältnis zum gesamten Marktvolumen.",
      tipp: "Beginnt mit „Markt“ und endet auf „-teil“.",
      loesung: "MARKTANTEIL",
      bestaetigung: "Richtig! Der Marktanteil zeigt, welchen Teil des Teilmarkts ein Unternehmen mit seinem Umsatz abdeckt.",
    },
    {
      nummer: 3,
      hinweis: "Analyse, die Stärken und Schwächen mit Chancen und Risiken vergleicht.",
      tipp: "Vier Buchstaben, die Anfangsbuchstaben der vier Felder.",
      loesung: "SWOT",
      bestaetigung: "Genau! Die SWOT-Analyse stellt interne Stärken und Schwächen den externen Chancen und Risiken gegenüber.",
    },
    {
      nummer: 4,
      hinweis: "Zentraler Knoten, in dem Sendungen gebündelt und neu verteilt werden.",
      tipp: "Englisch für „Nabe“; drei Buchstaben.",
      loesung: "HUB",
      bestaetigung: "Richtig! Im Hub werden Sendungen gebündelt und von dort auf die einzelnen Zielorte verteilt.",
    },
    {
      nummer: 5,
      hinweis: "Testlauf einer neuen Leistung mit ausgewählten Kunden.",
      tipp: "Kommt vor dem Rollout; fünf Buchstaben.",
      loesung: "PILOT",
      bestaetigung: "Genau! In der Pilotphase wird eine neue Leistung im kleinen Rahmen getestet, bevor sie breit eingeführt wird.",
    },
    {
      nummer: 6,
      hinweis: "Breite Einführung einer erprobten Leistung im ganzen Markt.",
      tipp: "Folgt auf den Pilotbetrieb; beginnt mit R.",
      loesung: "ROLLOUT",
      bestaetigung: "Richtig! Nach dem Pilotbetrieb folgt der Rollout für den gesamten Kundenstamm.",
    },
    {
      nummer: 7,
      hinweis: "Kosten, die unabhängig von der Leistungsmenge anfallen.",
      tipp: "Beispiel: Abschreibung auf Lkw. Gegenteil: variabel.",
      loesung: "FIXKOSTEN",
      bestaetigung: "Genau! Fixkosten fallen an, egal wie viel transportiert wird, zum Beispiel für Lkw oder Lagerhallen.",
    },
    {
      nummer: 8,
      hinweis: "Preisvorschlag an den Kunden, der nach der Kalkulation entsteht.",
      tipp: "Steht zwischen Kalkulation und Verhandlung.",
      loesung: "ANGEBOT",
      bestaetigung: "Richtig! Nach der Kalkulation wird das Angebot erstellt und dem Kunden vorgelegt.",
    },
    {
      nummer: 9,
      hinweis: "Software, die Planung, Durchführung und Kontrolle von Transporten unterstützt.",
      tipp: "Abkürzung aus drei Buchstaben, beginnt mit T.",
      loesung: "TMS",
      bestaetigung: "Genau! Ein Transportmanagementsystem unterstützt Tourenplanung, Auftragsabwicklung und Auswertung digital.",
    },
    {
      nummer: 10,
      hinweis: "Satellitenortung, mit der die Position eines Fahrzeugs bestimmt wird.",
      tipp: "Drei Buchstaben, bekannt vom Navigationsgerät.",
      loesung: "GPS",
      bestaetigung: "Richtig! Die GPS-Ortung ist ein Baustein von Track & Trace und zeigt, wo ein Fahrzeug gerade ist.",
    },
    {
      nummer: 11,
      hinweis: "Organisiert die Versendung des Gutes und muss nicht selbst fahren.",
      tipp: "Gegenstück zum Frachtführer, der selbst befördert.",
      loesung: "SPEDITEUR",
      bestaetigung: "Genau! Der Spediteur organisiert den Versand, zum Beispiel durch die Auswahl geeigneter Frachtführer.",
    },
    // Handlungsbereich 2: Transport, Lager, Verkehrsträger, Qualität
    {
      nummer: 12,
      hinweis: "Ordnet Fahrzeuge und Fahrpersonal den geplanten Fahrten zu.",
      tipp: "Arbeitet in der Dispositionszentrale.",
      loesung: "DISPONENT",
      bestaetigung: "Richtig! Der Disponent weist den geplanten Fahrten konkrete Fahrzeuge und Fahrpersonal zu.",
    },
    {
      nummer: 13,
      hinweis: "Route, auf der ein Fahrzeug mehrere Stellen nacheinander anfährt.",
      tipp: "Vier Buchstaben; ihre Planung nutzt das Sweep-Verfahren.",
      loesung: "TOUR",
      bestaetigung: "Genau! Eine Tour wird so geplant, dass Strecke, Ladekapazität und Kundenzeitfenster zusammenpassen.",
    },
    {
      nummer: 14,
      hinweis: "Flache Ladeeinheit, auf der Waren gestapelt im Lager stehen.",
      tipp: "Im Zeilenlager hat man Zugriff auf jede davon.",
      loesung: "PALETTE",
      bestaetigung: "Richtig! Im Regallager ist jede Palette direkt zugänglich.",
    },
    {
      nummer: 15,
      hinweis: "Ort, an dem Waren bis zum Weitertransport aufbewahrt werden.",
      tipp: "Fünf Buchstaben; Block, Zeile und Hochregal sind Arten.",
      loesung: "LAGER",
      bestaetigung: "Genau! Je nach Ware und Umschlag kommen verschiedene Lagerarten zum Einsatz.",
    },
    {
      nummer: 16,
      hinweis: "Menge an Waren, die gerade vorrätig ist.",
      tipp: "Wird durch den Verbrauch kleiner; beginnt mit B.",
      loesung: "BESTAND",
      bestaetigung: "Richtig! Der Bestand wird über Kennzahlen wie Reichweite und Umschlagshäufigkeit gesteuert.",
    },
    {
      nummer: 17,
      hinweis: "Band, das Ladung auf der Ladefläche festzieht und sichert.",
      tipp: "Damit wird niedergezurrt.",
      loesung: "ZURRGURT",
      bestaetigung: "Genau! Zurrgurte pressen die Ladung auf die Ladefläche und sichern sie gegen Verrutschen.",
    },
    {
      nummer: 18,
      hinweis: "Ladung liegt lückenlos an Wänden an und kann sich nicht bewegen.",
      tipp: "Gegenstück ist der Kraftschluss durch Reibung.",
      loesung: "FORMSCHLUSS",
      bestaetigung: "Richtig! Beim Formschluss hält die Form des Laderaums die Ladung an Ort und Stelle.",
    },
    {
      nummer: 19,
      hinweis: "Verkehrsträger für große Mengen über lange Strecken, an Fahrpläne gebunden.",
      tipp: "Hier fährt der Zug.",
      loesung: "SCHIENE",
      bestaetigung: "Genau! Die Schiene ist günstig und umweltfreundlich, aber weniger flexibel als die Straße.",
    },
    {
      nummer: 20,
      hinweis: "Verlagerung von Transporten von der Straße auf Bahn oder Binnenschiff.",
      tipp: "Zwei englische Wörter, zusammengeschrieben; zehn Buchstaben.",
      loesung: "MODALSHIFT",
      bestaetigung: "Richtig! Ein Modal Shift senkt den CO2-Ausstoß bei planbaren Großmengen auf langen Strecken.",
    },
    {
      nummer: 21,
      hinweis: "Beschwerde eines Kunden, zum Beispiel wegen Verspätung oder Transportschaden.",
      tipp: "Das Management dafür wertet die Ursachen aus.",
      loesung: "REKLAMATION",
      bestaetigung: "Genau! Aus Reklamationen leitet ein gutes Qualitätsmanagement Verbesserungen ab.",
    },
    {
      nummer: 22,
      hinweis: "Abgabe auf Waren, die aus Drittländern eingeführt werden.",
      tipp: "Vier Buchstaben; wird bei der Einfuhr angemeldet.",
      loesung: "ZOLL",
      bestaetigung: "Richtig! Beim Grenzübertritt aus Drittländern kommen zollrechtliche Verfahren ins Spiel.",
    },
    // Handlungsbereich 3: Führung, Kommunikation, Team, Ausbildung
    {
      nummer: 23,
      hinweis: "Psychologe, der menschliche Bedürfnisse als Pyramide ordnete.",
      tipp: "Seine Pyramide beginnt bei den körperlichen Bedürfnissen.",
      loesung: "MASLOW",
      bestaetigung: "Genau! Nach Maslow müssen niedrigere Stufen weitgehend erfüllt sein, bevor höhere motivieren.",
    },
    {
      nummer: 24,
      hinweis: "Beschrieb die Entwicklung von Teams in Phasen von Forming bis Performing.",
      tipp: "Nachname mit sieben Buchstaben, beginnt mit T.",
      loesung: "TUCKMAN",
      bestaetigung: "Richtig! Bruce Tuckman beschreibt typische Phasen der Teamentwicklung.",
    },
    {
      nummer: 25,
      hinweis: "Teamphase mit ersten Meinungsverschiedenheiten und Machtkämpfen.",
      tipp: "Folgt auf Forming und kommt vor Norming.",
      loesung: "STORMING",
      bestaetigung: "Genau! Die Storming-Phase ist ein normaler Teil der Teamentwicklung und kein Scheitern.",
    },
    {
      nummer: 26,
      hinweis: "Rückmeldung zu Verhalten, am besten konkret, zeitnah und als Ich-Botschaft.",
      tipp: "Englisches Wort mit acht Buchstaben.",
      loesung: "FEEDBACK",
      bestaetigung: "Richtig! Gutes Feedback ist konkret, verhaltensbezogen und zeitnah.",
    },
    {
      nummer: 27,
      hinweis: "Eine neutrale dritte Person moderiert das Gespräch bei einem Streit.",
      tipp: "Hilft bei festgefahrenen Konflikten; neun Buchstaben.",
      loesung: "MEDIATION",
      bestaetigung: "Genau! Bei einer Mediation gibt die neutrale Person keine Lösung vor, sondern begleitet die Parteien.",
    },
    {
      nummer: 28,
      hinweis: "Dem Gegenüber volle Aufmerksamkeit schenken und nachfragen.",
      tipp: "Gegenteil von Reden; acht Buchstaben.",
      loesung: "ZUHOEREN",
      bestaetigung: "Richtig! Aktives Zuhören sichert Verständnis und zeigt dem Kunden Wertschätzung.",
    },
    {
      nummer: 29,
      hinweis: "Anleitende Person im Betrieb, die Auszubildende fachlich begleitet.",
      tipp: "Macht bei der Vier-Stufen-Methode zuerst vor.",
      loesung: "AUSBILDER",
      bestaetigung: "Genau! Ausbildende vermitteln Fertigkeiten, zum Beispiel mit der Vier-Stufen-Methode.",
    },
    {
      nummer: 30,
      hinweis: "Kurzwort für eine Person, die im Betrieb einen Beruf lernt.",
      tipp: "Besucht auch die Berufsschule; fünf Buchstaben.",
      loesung: "AZUBI",
      bestaetigung: "Richtig! Azubis lernen im Betrieb und in der Berufsschule.",
    },
    {
      nummer: 31,
      hinweis: "Heft, in dem Auszubildende ihre Ausbildung festhalten.",
      tipp: "Wird auch Ausbildungsnachweis genannt.",
      loesung: "BERICHTSHEFT",
      bestaetigung: "Genau! Das Berichtsheft gehört zu den Pflichten der Auszubildenden.",
    },
    {
      nummer: 32,
      hinweis: "Matrix, die Aufgaben nach Wichtigkeit und Dringlichkeit ordnet.",
      tipp: "Ein Nachname mit zehn Buchstaben, beginnt mit E.",
      loesung: "EISENHOWER",
      bestaetigung: "Richtig! Die Eisenhower-Matrix hilft Führungskräften, Aufgaben zu priorisieren.",
    },
    {
      nummer: 33,
      hinweis: "Feste Arbeitsphase im Lager, zum Beispiel früh oder spät.",
      tipp: "Beim Wechsel braucht es eine Übergabe an die nächste Gruppe.",
      loesung: "SCHICHT",
      bestaetigung: "Genau! An der Schnittstelle zwischen den Schichten helfen klare Übergabeinformationen, Konflikte zu vermeiden.",
    },
  ],
  falschEinfachFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und vergleiche ihn mit den übrigen Wortkarten.",
  falschAnspruchsvollFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und prüfe auch die Buchstaben an den Kreuzungen.",
  unvollstaendigFeedback: "Hier fehlen noch Buchstaben. Du kannst das Wort weiter ausfüllen.",
  abschlussmeldung:
    "Geschafft! Du hast zehn Begriffe aus Vertrieb, Transport, Lager und Führung wiederholt. Jedes Rätsel ist anders — spiel gern noch eins!",
};
