import type { KreuzwortraetselPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, Nutzer-Vorgabe vom 06.10.2026): Wort-Pool „Versicherungen und Finanzanlagen" für das Kreuzworträtsel.
 * 34 kurze, alltagsnahe Begriffe aus allen vier Fachgebieten (KB1 Vorsorge, KB2 Gewerbekunden, KP1 Produkt/Kunde/Schaden/Leistung,
 * KP2 Steuerung/Führung/Projekt/Ausbildung); jedes Rätsel zieht zehn davon, das Gitter legt der Server bei jedem Start neu an
 * (kreuzwort-generator.ts). Bewusst ohne Rechtsdetails (keine Paragrafen, Zahlen, Fristen, Steuer- oder Beratungsrechtsregeln)
 * und ohne Produktempfehlungen — nur allgemeine Grundbegriffe aus der Kurstheorie. Inhalt bleibt bis zur Fachprüfung gesperrt.
 */
export const kreuzwortraetselVersicherung: KreuzwortraetselPayload = {
  wortzahl: 10,
  woerter: [
    // ---- Produkt, Kunde, Schaden und Leistung (KP1) ----
    {
      nummer: 1,
      loesung: "PRAEMIE",
      hinweis: "Das zahlt man regelmäßig dafür, dass der Versicherer das Risiko trägt.",
      tipp: "Beginnt mit P, sieben Buchstaben (AE = Ä).",
      bestaetigung: "Richtig! Die Prämie ist der Preis für den Versicherungsschutz.",
    },
    {
      nummer: 2,
      loesung: "POLICE",
      hinweis: "Die Urkunde, die den Versicherungsvertrag und seinen Umfang festhält.",
      tipp: "Beginnt mit P, sechs Buchstaben.",
      bestaetigung: "Genau! In der Police steht, was versichert ist.",
    },
    {
      nummer: 3,
      loesung: "RISIKO",
      hinweis: "Die Möglichkeit, dass ein Schaden eintritt.",
      tipp: "Gegenstück zur Sicherheit, sechs Buchstaben.",
      bestaetigung: "Richtig! Ein Risiko beschreibt, wie wahrscheinlich und wie teuer ein Schaden werden kann.",
    },
    {
      nummer: 4,
      loesung: "SCHADEN",
      hinweis: "Der finanzielle Verlust, den ein versichertes Ereignis verursacht.",
      tipp: "Gegenteil von Nutzen, sieben Buchstaben.",
      bestaetigung: "Genau! Ein Schaden löst im Versicherungsfall den Ablauf von Meldung bis Auszahlung aus.",
    },
    {
      nummer: 5,
      loesung: "TARIF",
      hinweis: "Das Modell aus Leistung und Preis, nach dem ein Versicherungsprodukt angeboten wird.",
      tipp: "Beginnt mit T, fünf Buchstaben.",
      bestaetigung: "Richtig! Im Tarif sind Leistungen und Preis eines Produkts festgelegt.",
    },
    {
      nummer: 6,
      loesung: "MAKLER",
      hinweis: "Unabhängiger Vermittler, der Angebote mehrerer Versicherer vergleichen kann.",
      tipp: "Gegenstück zum gebundenen Vertreter.",
      bestaetigung: "Genau! Der Makler ist neben dem Ausschließlichkeitsvertreter ein Vertriebsweg.",
    },
    {
      nummer: 7,
      loesung: "STORNO",
      hinweis: "Das vorzeitige Ende eines Vertrags, zum Beispiel durch Kündigung.",
      tipp: "Eine hohe Quote davon deutet auf Probleme hin.",
      bestaetigung: "Richtig! Viele Stornos können auf Probleme bei Beratung oder Service hindeuten.",
    },
    {
      nummer: 8,
      loesung: "REGRESS",
      hinweis: "Der Versicherer holt gezahltes Geld vom Verursacher des Schadens zurück.",
      tipp: "Beginnt mit R, sieben Buchstaben.",
      bestaetigung: "Genau! Beim Regress geht es um die Rückholung einer gezahlten Entschädigung beim Verursacher.",
    },
    {
      nummer: 9,
      loesung: "GUTACHTER",
      hinweis: "Sachverständige Person, die zum Beispiel die Höhe eines Schadens beurteilt.",
      tipp: "Beginnt mit G, neun Buchstaben.",
      bestaetigung: "Richtig! Bei größeren oder strittigen Fällen hilft eine Gutachterin oder ein Gutachter.",
    },
    {
      nummer: 10,
      loesung: "BEDARF",
      hinweis: "Das, was eine Kundin oder ein Kunde absichern muss; wird zu Beginn der Beratung erhoben.",
      tipp: "Die Analyse davon steht am Anfang jeder Beratung.",
      bestaetigung: "Genau! Der Bedarf ist der Ausgangspunkt jeder passenden Absicherung.",
    },
    // ---- Vorsorge (KB1) ----
    {
      nummer: 11,
      loesung: "RENTE",
      hinweis: "Regelmäßige Zahlung, zum Beispiel im Alter oder bei Berufsunfähigkeit.",
      tipp: "Beginnt mit R, fünf Buchstaben.",
      bestaetigung: "Richtig! Eine Rente wird regelmäßig gezahlt, oft ein Leben lang.",
    },
    {
      nummer: 12,
      loesung: "UNFALL",
      hinweis: "Ein plötzliches Ereignis, bei dem sich jemand verletzt.",
      tipp: "Die private Versicherung dafür ist ein Vorsorge-Baustein.",
      bestaetigung: "Genau! Die private Unfallversicherung schließt Lücken bei Unfällen in der Freizeit.",
    },
    {
      nummer: 13,
      loesung: "TAGEGELD",
      hinweis: "Eine vorab festgelegte Summe, die täglich ausgezahlt wird, zum Beispiel im Krankenhaus.",
      tipp: "Endet auf -GELD, acht Buchstaben.",
      bestaetigung: "Richtig! Ein Tagegeld wird als fester Betrag je Tag vereinbart.",
    },
    {
      nummer: 14,
      loesung: "PFLEGEGELD",
      hinweis: "Zahlung an Hilfebedürftige, die zu Hause von Angehörigen versorgt werden.",
      tipp: "Beginnt mit P, zehn Buchstaben.",
      bestaetigung: "Genau! Pflegegeld ist die Geldleistung, wenn nahestehende Personen die Versorgung übernehmen.",
    },
    {
      nummer: 15,
      loesung: "PFLEGELUECKE",
      hinweis: "Differenz zwischen den tatsächlichen Kosten bei Hilfsbedürftigkeit und der gesetzlichen Leistung.",
      tipp: "Zwölf Buchstaben; Ü steht als UE im Gitter.",
      bestaetigung: "Richtig! Die Pflegelücke ist der Teil der Kosten, den die Pflegeversicherung nicht übernimmt.",
    },
    {
      nummer: 16,
      loesung: "WARTEZEIT",
      hinweis: "Die Zeit nach Vertragsbeginn, in der noch keine Leistung gezahlt wird.",
      tipp: "Beginnt mit W, neun Buchstaben.",
      bestaetigung: "Genau! In der Wartezeit besteht noch kein Anspruch auf Leistung.",
    },
    {
      nummer: 17,
      loesung: "ZUSCHLAG",
      hinweis: "Ein Aufschlag auf den Beitrag, wenn das Risiko erhöht ist.",
      tipp: "Das Gegenteil von Rabatt, acht Buchstaben.",
      bestaetigung: "Richtig! Bei erhöhtem Risiko kann ein Zuschlag auf den Beitrag vereinbart werden.",
    },
    {
      nummer: 18,
      loesung: "FRAGEBOGEN",
      hinweis: "Formular, in dem Antragstellende zum Beispiel Vorerkrankungen angeben müssen.",
      tipp: "Beginnt mit F, zehn Buchstaben.",
      bestaetigung: "Genau! Mit dem Fragebogen erfasst der Versicherer das individuelle Risiko.",
    },
    // ---- Gewerbekunden (KB2) ----
    {
      nummer: 19,
      loesung: "BRAND",
      hinweis: "Feuer, das Gebäude oder Maschinen zerstört, etwa in einer Lackierkabine.",
      tipp: "Beginnt mit B, fünf Buchstaben.",
      bestaetigung: "Richtig! Brand gehört zu den klassischen Gefahren der Sachversicherung.",
    },
    {
      nummer: 20,
      loesung: "EINBRUCH",
      hinweis: "Gewaltsames Eindringen in Räume, bei dem Spuren zurückbleiben.",
      tipp: "Beginnt mit E, acht Buchstaben.",
      bestaetigung: "Genau! Bei einem Einbruch spielen nachweisbare Spuren eine wichtige Rolle.",
    },
    {
      nummer: 21,
      loesung: "ROHRBRUCH",
      hinweis: "Ein geplatztes Rohr: typische Ursache für einen Wasserschaden.",
      tipp: "Neun Buchstaben; endet auf -BRUCH.",
      bestaetigung: "Richtig! Ein Rohrbruch ist ein typischer Fall für Leitungswasserschäden.",
    },
    {
      nummer: 22,
      loesung: "RUECKSTAU",
      hinweis: "Wasser aus der Kanalisation drückt nach starkem Regen ins Gebäude zurück.",
      tipp: "Dagegen hilft eine Klappe; neun Buchstaben (UE = Ü).",
      bestaetigung: "Genau! Rückstau ist ein Elementarrisiko, gegen das man sich auch technisch schützen kann.",
    },
    {
      nummer: 23,
      loesung: "HAFTZEIT",
      hinweis: "Der Zeitraum, für den bei einer Betriebsunterbrechung der Ertragsausfall höchstens ersetzt wird.",
      tipp: "Beginnt mit H, acht Buchstaben.",
      bestaetigung: "Richtig! Die Haftzeit muss so lang sein, dass der Betrieb bis zur Wiederherstellung abgesichert ist.",
    },
    {
      nummer: 24,
      loesung: "ROHERTRAG",
      hinweis: "Entgangener Gewinn plus weiterlaufende Kosten; Grundlage bei der Betriebsunterbrechung.",
      tipp: "Beginnt mit R, neun Buchstaben.",
      bestaetigung: "Genau! Der Rohertrag bildet die Bemessungsgrundlage der Versicherungssumme bei Betriebsunterbrechung.",
    },
    {
      nummer: 25,
      loesung: "SELBSTBEHALT",
      hinweis: "Der Teil eines Schadens, den der Betrieb bewusst selbst trägt.",
      tipp: "Beginnt mit S, zwölf Buchstaben.",
      bestaetigung: "Richtig! Der Selbstbehalt gehört zum Selbst-Tragen, nicht zum Überwälzen.",
    },
    {
      nummer: 26,
      loesung: "CYBER",
      hinweis: "Vorsilbe für Risiken rund um Hackerangriffe und IT-Ausfall.",
      tipp: "Beginnt mit C, fünf Buchstaben.",
      bestaetigung: "Genau! Cyberrisiken betreffen Eigenschäden und Ansprüche Dritter nach einem IT-Vorfall.",
    },
    // ---- Steuerung, Führung, Projekt und Ausbildung (KP2) ----
    {
      nummer: 27,
      loesung: "BUDGET",
      hinweis: "Der für ein Jahr geplante Finanzrahmen einer Abteilung.",
      tipp: "Beginnt mit B, sechs Buchstaben; englisches Wort.",
      bestaetigung: "Richtig! Das Budget ist der Steuerungsrahmen für Neugeschäft, Kosten und Personal.",
    },
    {
      nummer: 28,
      loesung: "KENNZAHL",
      hinweis: "Messgröße zur Steuerung, zum Beispiel für Abschlüsse oder Schäden.",
      tipp: "Beginnt mit K, acht Buchstaben.",
      bestaetigung: "Genau! Kennzahlen machen Entwicklungen im Vertrieb messbar.",
    },
    {
      nummer: 29,
      loesung: "FEEDBACK",
      hinweis: "Rückmeldung zu einer Beobachtung, positiv oder kritisch.",
      tipp: "Englisches Wort, acht Buchstaben.",
      bestaetigung: "Richtig! Zeitnahes Feedback ist ein zentrales Führungsinstrument.",
    },
    {
      nummer: 30,
      loesung: "MENTOR",
      hinweis: "Erfahrene Person, die neue Kolleginnen und Kollegen langfristig begleitet.",
      tipp: "Beginnt mit M, sechs Buchstaben.",
      bestaetigung: "Genau! Ein Mentor begleitet über längere Zeit, anders als ein Coaching zu einem konkreten Thema.",
    },
    {
      nummer: 31,
      loesung: "PROJEKT",
      hinweis: "Ein zeitlich begrenztes, einmaliges Vorhaben mit eigenem Ziel.",
      tipp: "Beginnt mit P, sieben Buchstaben; kein Tagesgeschäft.",
      bestaetigung: "Richtig! Ein Projekt unterscheidet sich von wiederkehrenden Routineaufgaben.",
    },
    {
      nummer: 32,
      loesung: "PUFFER",
      hinweis: "Zeit, um die sich ein Vorgang verschieben darf, ohne das Projektende zu verschieben.",
      tipp: "Beginnt mit P, sechs Buchstaben.",
      bestaetigung: "Genau! Vorgänge ohne Puffer liegen auf dem kritischen Pfad.",
    },
    {
      nummer: 33,
      loesung: "ROTATION",
      hinweis: "In der Ausbildung der Durchlauf durch verschiedene Abteilungen nacheinander.",
      tipp: "Wie eine Drehung; acht Buchstaben.",
      bestaetigung: "Richtig! Durch die Rotation lernen Auszubildende alle wichtigen Bereiche kennen.",
    },
    {
      nummer: 34,
      loesung: "BERICHTSHEFT",
      hinweis: "Dort halten Auszubildende ihre vermittelten Lerninhalte schriftlich fest.",
      tipp: "Beginnt mit B, zwölf Buchstaben.",
      bestaetigung: "Genau! Das Berichtsheft dokumentiert die Ausbildungsinhalte und dient zugleich der Kontrolle.",
    },
  ],
  falschEinfachFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und vergleiche ihn mit den übrigen Begriffen.",
  falschAnspruchsvollFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und prüfe auch die Buchstaben an den Kreuzungen.",
  unvollstaendigFeedback: "Hier fehlen noch Buchstaben. Du kannst das Wort weiter ausfüllen.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe rund um Vorsorge, Gewerbekunden, Schaden und Leistung sowie Steuerung und Ausbildung wiederholt. Jedes Rätsel ist anders — spiel gern noch eins!",
};
