import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Memory-Pool „AEVO" — vier Themenrunden entsprechend den vier Handlungsfeldern, je zehn
 * Begriff-Bedeutung-Paare. Pro Spiel zieht der Server aus jeder Runde sechs Paare. Bewusst ohne Rechtsdetails (keine Paragrafen,
 * Fristen oder Zahlenwerte). Entwurf, bis zur Fachprüfung gesperrt.
 */
export const memoryAevo: MemoryPayload = {
  runden: [
    {
      nummer: 1,
      titel: "Voraussetzungen prüfen und Ausbildung planen",
      abschlussmeldung: "Geschafft! Du kennst jetzt zentrale Begriffe rund um Ausbildungsbedarf, Eignung des Betriebs und Kooperationsformen.",
    },
    {
      nummer: 2,
      titel: "Ausbildung vorbereiten und mitwirken",
      abschlussmeldung: "Geschafft! Du kannst Ausbildungsordnung, Ausbildungsplan, Mitwirkende und Vertragsvorbereitung jetzt auseinanderhalten.",
    },
    {
      nummer: 3,
      titel: "Ausbildung durchführen",
      abschlussmeldung: "Geschafft! Du erkennst jetzt Lernzielbereiche, Methoden, Rückmeldeformen und typische Beurteilungsfehler.",
    },
    {
      nummer: 4,
      titel: "Ausbildung abschließen",
      abschlussmeldung: "Geschafft! Du kennst jetzt die Begriffe rund um Abschlussprüfung, Zeugnis und berufliche Perspektiven.",
    },
  ],
  paareProRunde: 6,
  paare: [
    // Runde 1 — Handlungsfeld 1
    {
      nummer: 1,
      runde: 1,
      begriff: "Duales System",
      bedeutung: "Ausbildung an zwei Lernorten: Betrieb und Schule",
      bestaetigung: "Richtig! Im dualen System wird gleichzeitig im Betrieb und in der Berufsschule gelernt.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Zuständige Stelle",
      bedeutung: "Kammer, die Verträge einträgt und Prüfungen abnimmt",
      bestaetigung: "Genau! Für Kelvinar als Industrieunternehmen ist das die IHK.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Ausbildungsrahmenplan",
      bedeutung: "Bundesweite sachliche und zeitliche Gliederung",
      bestaetigung: "Richtig! Er legt fest, welche Inhalte in welcher Reihenfolge vermittelt werden sollen.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Sachliche Eignung",
      bedeutung: "Ausstattung des Betriebs reicht für alle Inhalte",
      bestaetigung: "Genau! Dazu gehören zum Beispiel Maschinen, Werkzeuge und die Ausbildungswerkstatt.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Personelle Eignung",
      bedeutung: "Genug passend qualifizierte Ausbilder:innen vorhanden",
      bestaetigung: "Richtig! Dazu zählt auch ein passendes Verhältnis von Ausbilder:innen zu Azubis.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Verbundausbildung",
      bedeutung: "Mehrere Betriebe teilen sich die Ausbildung",
      bestaetigung: "Genau! Jeder Partnerbetrieb vermittelt die Inhalte, für die er am besten ausgestattet ist.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Überbetriebliche Ausbildung",
      bedeutung: "Ergänzende Lehrgänge außerhalb des eigenen Betriebs",
      bestaetigung: "Richtig! Sie vermittelt Fertigkeiten, die der Betrieb selbst nicht oder nicht wirtschaftlich vermitteln kann.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Einstiegsqualifizierung",
      bedeutung: "Betriebliches Langzeitpraktikum zum Kennenlernen",
      bestaetigung: "Genau! So lernt der Betrieb Bewerbende mit Potenzial und offenen Lücken vor dem Vertrag kennen.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Fachkräftesicherung",
      bedeutung: "Eigenen Nachwuchs ausbilden, statt extern zu suchen",
      bestaetigung: "Richtig! Das ist einer der wichtigsten Vorteile betrieblicher Ausbildung.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Ausbildungsbedarf",
      bedeutung: "Wie viele Fachkräfte der Betrieb künftig braucht",
      bestaetigung: "Genau! Er ergibt sich aus betrieblichen, rechtlichen und tarifvertraglichen Grundlagen.",
    },
    // Runde 2 — Handlungsfeld 2
    {
      nummer: 11,
      runde: 2,
      begriff: "Ausbildungsordnung",
      bedeutung: "Bundeseinheitliche Vorgabe für einen anerkannten Beruf",
      bestaetigung: "Richtig! Jeder anerkannte Ausbildungsberuf hat eine eigene Ausbildungsordnung.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Ausbildungsberufsbild",
      bedeutung: "Beschreibt, was am Ende gekonnt werden soll",
      bestaetigung: "Genau! Es beschreibt die Fertigkeiten, Kenntnisse und Fähigkeiten, die das Ausbildungsziel sind.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Betrieblicher Ausbildungsplan",
      bedeutung: "Setzt den Rahmenplan im eigenen Betrieb um",
      bestaetigung: "Richtig! Er enthält eine zeitliche und eine sachliche Gliederung für die Stationen im Betrieb.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Rahmenlehrplan",
      bedeutung: "Lehrplan der Berufsschule, mit dem Betrieb abgestimmt",
      bestaetigung: "Genau! Er ist mit dem Ausbildungsrahmenplan abgestimmt.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Lernortkooperation",
      bedeutung: "Betrieb und Schule stimmen sich miteinander ab",
      bestaetigung: "Richtig! So überschneiden sich die Inhalte beider Lernorte nicht und lassen keine Lücken.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Betriebsrat",
      bedeutung: "Gewählte Vertretung der Beschäftigten im Betrieb",
      bestaetigung: "Genau! Bei bestimmten Themen der Berufsbildung ist er zu beteiligen.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Jugendvertretung (JAV)",
      bedeutung: "Vertritt die jungen Beschäftigten und Azubis im Betrieb",
      bestaetigung: "Richtig! Sie ist bei Kelvinar das Sprachrohr der Auszubildenden über die Fachabteilungen hinweg.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Einstellungstest",
      bedeutung: "Prüft fachliche Grundlagen der Bewerbenden",
      bestaetigung: "Genau! Er wird oft mit Bewerbungsunterlagen und Vorstellungsgespräch kombiniert.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Ausbildungsvertrag",
      bedeutung: "Hält Rechte und Pflichten beider Seiten fest",
      bestaetigung: "Richtig! Der betriebliche Ausbildungsplan wird dem Vertrag beigefügt.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Berichtsheft",
      bedeutung: "Fortlaufender Nachweis der gelernten Inhalte",
      bestaetigung: "Genau! Es dient der Dokumentation und hilft, Lücken im Ausbildungsverlauf früh zu erkennen.",
    },
    // Runde 3 — Handlungsfeld 3
    {
      nummer: 21,
      runde: 3,
      begriff: "Feedback",
      bedeutung: "Konkrete, zeitnahe Rückmeldung zum Verhalten",
      bestaetigung: "Richtig! Gutes Feedback ist konkret, zeitnah und zweiseitig.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Sandwich-Methode",
      bedeutung: "Lob, Verbesserungshinweis, ermutigender Abschluss",
      bestaetigung: "Genau! Sie sollte nicht schematisch genutzt werden, denn unehrliches Lob fällt schnell auf.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "4-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen, Üben",
      bestaetigung: "Richtig! Sie eignet sich besonders für neue, sicherheitsrelevante Handgriffe.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Leittextmethode",
      bedeutung: "Leitfragen führen zum selbstständigen Erarbeiten",
      bestaetigung: "Genau! Sie passt zu komplexeren, offeneren Aufgaben.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Kognitives Lernziel",
      bedeutung: "Wissen und Denken (Kopf)",
      bestaetigung: "Richtig! Dazu gehören Fakten kennen, Zusammenhänge verstehen und Probleme lösen.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "Affektives Lernziel",
      bedeutung: "Einstellungen und Haltungen (Herz)",
      bestaetigung: "Genau! Haltungen lassen sich nicht vortragen, sie entwickeln sich durch Vorbild und Erfahrung.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Psychomotorisches Lernziel",
      bedeutung: "Fertigkeiten und Handgriffe (Hand)",
      bestaetigung: "Richtig! Solche Fertigkeiten erwirbt man durch Vormachen, Nachmachen und Üben.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Halo-Effekt",
      bedeutung: "Ein auffälliges Merkmal überstrahlt alles andere",
      bestaetigung: "Genau! Ein einzelnes starkes Merkmal färbt dann das ganze Urteil.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Tendenz zur Mitte",
      bedeutung: "Extreme Urteile werden aus Unsicherheit gemieden",
      bestaetigung: "Richtig! Dann bekommen alle ein mittleres Urteil, obwohl die Leistungen weit auseinanderliegen.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Recency-Effekt",
      bedeutung: "Zuletzt Beobachtetes zählt überproportional",
      bestaetigung: "Genau! Wer Beobachtungen über den ganzen Zeitraum notiert, beugt dem vor.",
    },
    // Runde 4 — Handlungsfeld 4
    {
      nummer: 31,
      runde: 4,
      begriff: "Abschlussprüfung",
      bedeutung: "Prüfung bei der Kammer am Ende der Ausbildung",
      bestaetigung: "Richtig! Auf sie bereiten Ausbildende die Azubis über die gesamte Ausbildungszeit vor.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Gestreckte Abschlussprüfung",
      bedeutung: "Erster Teil zur Halbzeit, zweiter Teil am Ende",
      bestaetigung: "Genau! Deshalb planen Ausbildende Wiederholungsphasen vor beiden Terminen.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Zulassung",
      bedeutung: "Erlaubnis, an der Abschlussprüfung teilzunehmen",
      bestaetigung: "Richtig! Dafür müssen bestimmte Voraussetzungen erfüllt sein, zum Beispiel ein geführtes Berichtsheft.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Anmeldung",
      bedeutung: "Meldung zum Prüfungstermin bei der zuständigen Stelle",
      bestaetigung: "Genau! Eine zentrale Terminübersicht hilft, keine Frist zu verpassen.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Nachteilsausgleich",
      bedeutung: "Angepasste Prüfungsbedingungen bei Behinderung",
      bestaetigung: "Richtig! Er muss rechtzeitig beantragt werden, nicht erst am Prüfungstag.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Ausbildungszeugnis",
      bedeutung: "Schriftlicher Nachweis des Betriebs über die Ausbildung",
      bestaetigung: "Genau! Es ist vom Prüfungszeugnis der Kammer zu unterscheiden.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Qualifiziertes Zeugnis",
      bedeutung: "Enthält zusätzlich Führung und Leistung",
      bestaetigung: "Richtig! Das einfache Zeugnis nennt nur Art, Dauer und Ziel der Ausbildung.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "Zeugniswahrheit",
      bedeutung: "Die Aussagen im Zeugnis müssen zutreffen",
      bestaetigung: "Genau! Dazu kommen Zeugnisklarheit und ein wohlwollender Gesamtton.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Übernahme",
      bedeutung: "Weiterbeschäftigung nach bestandener Prüfung",
      bestaetigung: "Richtig! Darüber sprechen Ausbildende in einem Perspektivgespräch vor Ausbildungsende.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Fachwirt",
      bedeutung: "Kammer-Fortbildung als Aufstieg nach der Ausbildung",
      bestaetigung: "Genau! Sie baut auf der Erstausbildung und Berufserfahrung auf.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Begriffe aus allen vier Handlungsfeldern der Ausbildung der Ausbilder wiederholt. Wähle „Noch einmal spielen“ — dann liegen neue Karten auf dem Tisch.",
};
