import type { BugHuntPayload } from "@edukedo/shared";

/**
 * Gaming-Tab: „Bug-Hunt: Finde die fehlerhafte Zeile" für die Fachinformatiker/in-Kurse
 * (12 kurze Codeausschnitte in Python, JavaScript, Java und SQL, in jedem steckt genau ein Fehler in genau einer Zeile).
 * Die Schwierigkeit steigt über die Aufgaben hinweg an.
 */
export const bugHuntCodefehler: BugHuntPayload = {
  aufgaben: [
    {
      nummer: 1,
      titel: "Summe der Zahlen von 1 bis n",
      sprache: "Python",
      aufgabe: "Die Funktion soll die Summe aller ganzen Zahlen von 1 bis einschließlich n berechnen. Für n = 4 soll 10 herauskommen.",
      zeilen: [
        "def summe_bis(n):",
        "    summe = 0",
        "    for zahl in range(1, n):",
        "        summe += zahl",
        "    return summe",
      ],
      fehlerZeile: 3,
      tipp: "Prüfe, wie oft die Schleife läuft und welche Zahlen sie tatsächlich durchläuft.",
      korrektur: "    for zahl in range(1, n + 1):",
      erklaerung:
        "range(1, n) endet vor dem Wert n, die Obergrenze gehört nicht mehr dazu. Für n = 4 werden nur 1, 2 und 3 addiert, also 6 statt 10. Mit range(1, n + 1) wird auch n selbst addiert. Das ist ein klassischer Off-by-one-Fehler (Abweichung um eins).",
    },
    {
      nummer: 2,
      titel: "Mittelwert einer Liste",
      sprache: "Python",
      aufgabe: "Die Funktion soll den Mittelwert der übergebenen Zahlen als Ergebnis an den Aufrufer zurückgeben, damit er damit weiterrechnen kann.",
      zeilen: [
        "def mittelwert(werte):",
        "    gesamt = 0",
        "    for wert in werte:",
        "        gesamt += wert",
        "    durchschnitt = gesamt / len(werte)",
        "    print(durchschnitt)",
      ],
      fehlerZeile: 6,
      tipp: "Frage dich, was der Aufrufer der Funktion eigentlich in den Händen hält, wenn er sie aufruft und das Ergebnis speichern will.",
      korrektur: "    return durchschnitt",
      erklaerung:
        "print gibt den Wert nur auf der Konsole aus, die Funktion selbst liefert dann None zurück. Wer ergebnis = mittelwert([2, 4]) schreibt, bekommt None statt 3.0. Erst return reicht den berechneten Wert an den Aufrufer weiter.",
    },
    {
      nummer: 3,
      titel: "Aktive Nutzer zählen",
      sprache: "JavaScript",
      aufgabe: "Die Funktion soll zählen, wie viele Personen in der Liste den Status \"aktiv\" haben.",
      zeilen: [
        "function zaehleAktive(nutzer) {",
        "  let anzahl = 0;",
        "  for (const person of nutzer) {",
        "    if (person.status = \"aktiv\") {",
        "      anzahl++;",
        "    }",
        "  }",
        "  return anzahl;",
        "}",
      ],
      fehlerZeile: 4,
      tipp: "Sieh dir genau an, welches Zeichen in der Bedingung steht und was es mit dem Wert von person.status macht.",
      korrektur: "    if (person.status === \"aktiv\") {",
      erklaerung:
        "Ein einzelnes = ist eine Zuweisung, kein Vergleich. Der Ausdruck setzt person.status auf \"aktiv\" und liefert diesen nicht leeren Text, der als wahr gilt. Dadurch zählt jede Person als aktiv und ihr Status wird sogar überschrieben. Verglichen wird mit === (strikter Vergleich).",
    },
    {
      nummer: 4,
      titel: "Inaktive Kunden markieren",
      sprache: "SQL",
      aufgabe:
        "Das Skript soll nur diejenigen Kunden auf den Status 'inaktiv' setzen, deren letzter Login vor dem 01.01.2025 liegt. Alle anderen Kunden sollen unverändert bleiben.",
      zeilen: [
        "SELECT COUNT(*) AS betroffene_kunden",
        "FROM kunde",
        "WHERE letzter_login < '2025-01-01';",
        "UPDATE kunde SET status = 'inaktiv';",
        "SELECT status, COUNT(*) AS anzahl",
        "FROM kunde",
        "GROUP BY status;",
      ],
      fehlerZeile: 4,
      tipp: "Überlege, welche Zeilen der Tabelle von dieser Anweisung verändert werden.",
      korrektur: "UPDATE kunde SET status = 'inaktiv' WHERE letzter_login < '2025-01-01';",
      erklaerung:
        "Ohne WHERE-Klausel wirkt ein UPDATE auf alle Zeilen der Tabelle. Hier würden also sämtliche Kunden deaktiviert, nicht nur die mit altem Login. Mit der Bedingung aus der ersten Abfrage ist nur die gewünschte Teilmenge betroffen. Zur Vorsicht prüft man eine WHERE-Bedingung vorher mit einem SELECT, wie es die ersten Zeilen tun.",
    },
    {
      nummer: 5,
      titel: "Ziffern zählen",
      sprache: "Python",
      aufgabe: "Die Funktion soll zählen, wie viele Ziffern eine positive ganze Zahl hat. Für 482 soll 3 herauskommen.",
      zeilen: [
        "def anzahl_ziffern(zahl):",
        "    anzahl = 0",
        "    while zahl > 0:",
        "        anzahl += 1",
        "        zahl // 10",
        "    return anzahl",
      ],
      fehlerZeile: 5,
      tipp: "Die Schleife läuft, solange die Bedingung wahr ist. Wird der Wert, der in der Bedingung geprüft wird, irgendwo verändert?",
      korrektur: "        zahl = zahl // 10",
      erklaerung:
        "Der Ausdruck zahl // 10 berechnet zwar das Ergebnis der ganzzahligen Division, speichert es aber nirgends. zahl behält ihren Wert, die Bedingung zahl > 0 bleibt dauerhaft wahr, und die Schleife endet nie (Endlosschleife). Erst die Zuweisung zahl = zahl // 10 schneidet in jedem Durchlauf eine Ziffer ab, bis 0 erreicht ist.",
    },
    {
      nummer: 6,
      titel: "Rechnungsbeträge ausgeben",
      sprache: "JavaScript",
      aufgabe: "Die Funktion soll Netto, Mehrwertsteuer und Brutto ausgeben. Für netto = 100 und mwst = 19 soll in der letzten Zeile \"Brutto: 119 EUR\" stehen.",
      zeilen: [
        "function rechnungAusgeben(netto, mwst) {",
        "  console.log(\"Netto: \" + netto + \" EUR\");",
        "  console.log(\"MwSt: \" + mwst + \" EUR\");",
        "  console.log(\"Brutto: \" + netto + mwst + \" EUR\");",
        "  return netto + mwst;",
        "}",
      ],
      fehlerZeile: 4,
      tipp: "Der Operator + kann Zahlen addieren oder Texte verketten. Von links nach rechts gelesen: Was passiert direkt nach dem ersten Text?",
      korrektur: "  console.log(\"Brutto: \" + (netto + mwst) + \" EUR\");",
      erklaerung:
        "Die Ausdrücke werden von links nach rechts ausgewertet. Sobald links ein Text steht, verkettet + auch die folgenden Zahlen als Text: \"Brutto: \" + 100 ergibt \"Brutto: 100\", dann wird 19 angehängt, und es erscheint \"Brutto: 10019 EUR\". Die Klammer (netto + mwst) erzwingt zuerst die Addition der Zahlen.",
    },
    {
      nummer: 7,
      titel: "Durchschnitt eines Arrays",
      sprache: "Java",
      aufgabe: "Die Methode soll den Durchschnitt der Werte als Kommazahl liefern. Für {2, 3} soll 2.5 herauskommen.",
      zeilen: [
        "public static double durchschnitt(int[] werte) {",
        "    if (werte.length == 0) {",
        "        return 0;",
        "    }",
        "    int summe = 0;",
        "    for (int wert : werte) {",
        "        summe += wert;",
        "    }",
        "    return summe / werte.length;",
        "}",
      ],
      fehlerZeile: 9,
      tipp: "Achte auf die Datentypen der beiden Operanden der Division. Welcher Typ kommt bei int geteilt durch int heraus?",
      korrektur: "    return (double) summe / werte.length;",
      erklaerung:
        "In Java ist die Division von zwei int-Werten eine Ganzzahldivision, der Nachkommaanteil wird abgeschnitten: 5 / 2 ergibt 2. Erst danach wird das Ergebnis in double umgewandelt, also 2.0 statt 2.5. Der Cast (double) vor summe macht daraus eine Division mit Kommazahl.",
    },
    {
      nummer: 8,
      titel: "Punkte in Noten umrechnen",
      sprache: "JavaScript",
      aufgabe: "Die Funktion soll ab 90 Punkten \"sehr gut\", ab 75 Punkten \"gut\", ab 50 Punkten \"ausreichend\" und sonst \"nicht bestanden\" zurückgeben. Genau 90 Punkte sollen also \"sehr gut\" ergeben.",
      zeilen: [
        "function note(punkte) {",
        "  if (punkte > 90) {",
        "    return \"sehr gut\";",
        "  }",
        "  if (punkte >= 75) {",
        "    return \"gut\";",
        "  }",
        "  if (punkte >= 50) {",
        "    return \"ausreichend\";",
        "  }",
        "  return \"nicht bestanden\";",
        "}",
      ],
      fehlerZeile: 2,
      tipp: "Randfälle sind beliebte Fehlerquellen. Was passiert bei genau 90 Punkten?",
      korrektur: "  if (punkte >= 90) {",
      erklaerung:
        "\"Ab 90 Punkten\" schließt die 90 mit ein, dafür braucht es >=. Mit > fällt der Grenzwert 90 durch die erste Bedingung und landet bei \"gut\". Grenzwerte sollte man immer mit einem Testfall genau auf der Grenze prüfen.",
    },
    {
      nummer: 9,
      titel: "Kleinste Zahl finden",
      sprache: "Python",
      aufgabe: "Die Funktion soll die kleinste Zahl einer nicht leeren Liste beliebiger Zahlen zurückgeben. Für [4, 7, 5] soll 4 herauskommen.",
      zeilen: [
        "def kleinste_zahl(zahlen):",
        "    kleinste = 0",
        "    for zahl in zahlen:",
        "        if zahl < kleinste:",
        "            kleinste = zahl",
        "    return kleinste",
      ],
      fehlerZeile: 2,
      tipp: "Teste die Funktion gedanklich mit einer Liste, die nur positive Zahlen enthält. Womit wird jede Zahl verglichen?",
      korrektur: "    kleinste = zahlen[0]",
      erklaerung:
        "Der Startwert 0 ist selbst kein Element der Liste. Sind alle Zahlen größer als 0, ist keine kleiner als der Startwert, und die Funktion gibt fälschlich 0 zurück. Beim Suchen von Minimum oder Maximum startet man mit dem ersten Element der Liste, damit der Vergleich immer von einem echten Listenwert ausgeht.",
    },
    {
      nummer: 10,
      titel: "Große Abteilungen auswerten",
      sprache: "SQL",
      aufgabe: "Die Abfrage soll alle Abteilungen mit mehr als fünf Mitarbeitenden ausgeben, dazu die Anzahl und das Durchschnittsgehalt, absteigend nach Durchschnittsgehalt sortiert.",
      zeilen: [
        "SELECT abteilung, COUNT(*) AS anzahl, AVG(gehalt) AS durchschnitt",
        "FROM mitarbeiter",
        "GROUP BY abteilung",
        "WHERE COUNT(*) > 5",
        "ORDER BY durchschnitt DESC;",
      ],
      fehlerZeile: 4,
      tipp: "Die Bedingung bezieht sich auf das Ergebnis einer Gruppierung, nicht auf einzelne Zeilen der Tabelle.",
      korrektur: "HAVING COUNT(*) > 5",
      erklaerung:
        "WHERE filtert einzelne Zeilen vor der Gruppierung und kennt die Ergebnisse von Aggregatfunktionen wie COUNT(*) noch nicht. Bedingungen auf Gruppen gehören nach GROUP BY in eine HAVING-Klausel. Außerdem steht WHERE niemals hinter GROUP BY, die Abfrage wäre so nicht einmal syntaktisch gültig.",
    },
    {
      nummer: 11,
      titel: "Werte über einer Grenze zählen",
      sprache: "Java",
      aufgabe: "Die Methode soll zählen, wie viele Werte im Array größer als die übergebene Grenze sind. Sie soll auch bei längeren Arrays ohne Fehlermeldung durchlaufen.",
      zeilen: [
        "public static int zaehleGroesser(int[] werte, int grenze) {",
        "    int anzahl = 0;",
        "    for (int i = 0; i <= werte.length; i++) {",
        "        if (werte[i] > grenze) {",
        "            anzahl++;",
        "        }",
        "    }",
        "    return anzahl;",
        "}",
      ],
      fehlerZeile: 3,
      tipp: "Bei einem Array mit vier Elementen: Welche Indizes sind erlaubt, und welchen Wert hat i im letzten Schleifendurchlauf?",
      korrektur: "    for (int i = 0; i < werte.length; i++) {",
      erklaerung:
        "Array-Indizes laufen von 0 bis length - 1. Mit i <= werte.length wird im letzten Durchlauf auf werte[werte.length] zugegriffen, das Element gibt es nicht, und Java wirft eine ArrayIndexOutOfBoundsException. Die Schleife muss mit i < werte.length abbrechen.",
    },
    {
      nummer: 12,
      titel: "Bestellungen mit Kundennamen",
      sprache: "SQL",
      aufgabe: "Die Abfrage soll zu jeder Bestellung über 100 Euro den Namen des Kunden anzeigen, der sie aufgegeben hat. Jede Bestellung soll genau einmal vorkommen.",
      zeilen: [
        "SELECT k.name,",
        "       b.id,",
        "       b.betrag",
        "FROM kunde k, bestellung b",
        "WHERE b.betrag > 100",
        "ORDER BY k.name;",
      ],
      fehlerZeile: 5,
      tipp: "Welche Bedingung verbindet eine Bestellung mit genau einem passenden Kunden? Überlege, was ohne eine solche Bedingung bei zwei Tabellen herauskommt.",
      korrektur: "WHERE b.kunde_id = k.id AND b.betrag > 100",
      erklaerung:
        "Ohne Verknüpfungsbedingung zwischen kunde und bestellung bildet die Datenbank das kartesische Produkt: Jede Bestellung über 100 Euro wird mit jedem Kunden kombiniert. Das Ergebnis enthält viel zu viele Zeilen mit falschen Zuordnungen. Die Bedingung b.kunde_id = k.id verknüpft Fremdschlüssel und Primärschlüssel. Heute schreibt man das meist als JOIN ... ON.",
    },
  ],
  abschlussmeldung:
    "Geschafft! Du hast zwölf Fehlerzeilen aufgespürt und dabei typische Fehlerklassen kennengelernt: Off-by-one-Fehler bei Schleifen und Indizes, Zuweisung statt Vergleich, ein fehlendes return, Endlosschleifen ohne veränderten Zähler, Ganzzahldivision, falsche Startwerte, falsche Vergleichsoperatoren an Grenzwerten, Text- statt Zahlenverknüpfung sowie in SQL fehlende WHERE- und JOIN-Bedingungen und WHERE statt HAVING bei Aggregaten. Wer diese Muster kennt, findet Bugs im eigenen Code deutlich schneller.",
};
