import type { KreuzwortraetselPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, 06.10.2026): Wort-Pool „AEVO" für das Kreuzworträtsel. 34 kurze, alltagsnahe Begriffe aus der Kurstheorie
 * (HF1 Voraussetzungen und Planung, HF2 Ausbildung vorbereiten, HF3 Ausbildung durchführen, HF4 Ausbildung abschließen).
 * Der Server legt bei jedem Start eine neue Auswahl von zehn Wörtern und ein neues Gitter an; Positionen sind deshalb nicht hinterlegt.
 * Bewusst ohne Rechtsdetails (keine Paragrafen, Fristen oder Zahlenwerte). Entwurf, bis zur Fachprüfung gesperrt.
 */
export const kreuzwortraetselAevo: KreuzwortraetselPayload = {
  wortzahl: 10,
  woerter: [
    // HF1 — Ausbildungsvoraussetzungen prüfen und Ausbildung planen
    {
      nummer: 1,
      hinweis: "Kurzwort für eine Person, die gerade eine Berufsausbildung macht.",
      tipp: "Fünf Buchstaben, beginnt mit A.",
      loesung: "AZUBI",
      bestaetigung: "Richtig! Azubis lernen im Betrieb und in der Berufsschule und werden von Ausbilder:innen begleitet.",
    },
    {
      nummer: 2,
      hinweis: "Für Kelvinar die zuständige Stelle: Sie trägt Verträge ein und nimmt die Abschlussprüfung ab.",
      tipp: "Drei Buchstaben, das K steht für Kammer.",
      loesung: "IHK",
      bestaetigung: "Genau! Die IHK ist für Kelvinar als Industrieunternehmen die zuständige Stelle.",
    },
    {
      nummer: 3,
      hinweis: "Lernort für die Theorie, neben dem Betrieb.",
      tipp: "Zwölf Buchstaben, beginnt mit B.",
      loesung: "BERUFSSCHULE",
      bestaetigung: "Richtig! Die Berufsschule vermittelt den theoretischen Teil und meldet Auffälligkeiten wie Fehlzeiten an den Betrieb zurück.",
    },
    {
      nummer: 4,
      hinweis: "System der Ausbildung an zwei Lernorten, Betrieb und Schule.",
      tipp: "Vier Buchstaben, bedeutet „doppelt“ oder „zweifach“.",
      loesung: "DUAL",
      bestaetigung: "Genau! Im dualen System wird gleichzeitig im Betrieb und in der Berufsschule gelernt.",
    },
    {
      nummer: 5,
      hinweis: "Das prüft die Kammer beim Betrieb: Passen Ausstattung und Ausbildungspersonal?",
      tipp: "Wird sachlich und personell unterschieden.",
      loesung: "EIGNUNG",
      bestaetigung: "Richtig! Die Eignung des Betriebs hat eine sachliche und eine personelle Seite.",
    },
    {
      nummer: 6,
      hinweis: "Mehrere Betriebe teilen sich die Ausbildung einer Person arbeitsteilig.",
      tipp: "Ergänzt man „-ausbildung“, entsteht der ganze Begriff.",
      loesung: "VERBUND",
      bestaetigung: "Genau! Bei der Verbundausbildung vermittelt jeder Partnerbetrieb die Inhalte, für die er am besten ausgestattet ist.",
    },
    {
      nummer: 7,
      hinweis: "Gut qualifizierte Person im Beruf; in Elektrotechnik und IT wird sie knapp.",
      tipp: "Neun Buchstaben, dazu passt „-mangel“.",
      loesung: "FACHKRAFT",
      bestaetigung: "Stimmt! Wer selbst ausbildet, sichert sich Fachkräfte, die den Betrieb schon kennen.",
    },
    {
      nummer: 8,
      hinweis: "Zeit im Betrieb zum Kennenlernen; bei der Einstiegsqualifizierung ein langes.",
      tipp: "Beginnt mit P, neun Buchstaben.",
      loesung: "PRAKTIKUM",
      bestaetigung: "Richtig! Ein Praktikum hilft, Bewerbende mit Potenzial vor einem Ausbildungsvertrag kennenzulernen.",
    },
    {
      nummer: 9,
      hinweis: "Person im Betrieb, die Auszubildende anleitet und ihnen Können vermittelt.",
      tipp: "Kann hauptamtlich oder nebenberuflich arbeiten.",
      loesung: "AUSBILDER",
      bestaetigung: "Genau! Ausbilder:innen in den Fachabteilungen vermitteln die fachpraktischen Inhalte vor Ort.",
    },
    // HF2 — Ausbildung vorbereiten und bei der Einstellung mitwirken
    {
      nummer: 10,
      hinweis: "Legt fest, wann ein Azubi welche Station im Betrieb durchläuft.",
      tipp: "Vier Buchstaben, oft „betrieblicher ...“.",
      loesung: "PLAN",
      bestaetigung: "Genau! Der betriebliche Ausbildungsplan übersetzt den Rahmenplan in den Betriebsalltag.",
    },
    {
      nummer: 11,
      hinweis: "Abschnitt der Ausbildung in einer Abteilung, z. B. Einkauf oder IT.",
      tipp: "Sieben Buchstaben; ein Halt auf dem Weg.",
      loesung: "STATION",
      bestaetigung: "Richtig! Azubis durchlaufen nacheinander mehrere Stationen im Betrieb.",
    },
    {
      nummer: 12,
      hinweis: "Gewählte Vertretung der Beschäftigten im Betrieb.",
      tipp: "Elf Buchstaben; bei Ausbildungsthemen beteiligt.",
      loesung: "BETRIEBSRAT",
      bestaetigung: "Richtig! Der Betriebsrat hat bei bestimmten Themen der Berufsbildung Mitwirkungs- oder Informationsrechte.",
    },
    {
      nummer: 13,
      hinweis: "Verschiedene Herkunft und Wege von Bewerbenden sehen wir als Chance.",
      tipp: "Fachwort dafür: Diversität.",
      loesung: "VIELFALT",
      bestaetigung: "Genau! Vielfalt wird bei Kelvinar als Stärke gesehen, nicht als Störung.",
    },
    {
      nummer: 14,
      hinweis: "Wird vor Ausbildungsbeginn zwischen Betrieb und Azubi geschlossen.",
      tipp: "Sieben Buchstaben; beide Seiten sind daran gebunden.",
      loesung: "VERTRAG",
      bestaetigung: "Richtig! Der Berufsausbildungsvertrag hält die Rechte und Pflichten beider Seiten fest und wird bei der Kammer eingetragen.",
    },
    {
      nummer: 15,
      hinweis: "Hier halten Azubis fortlaufend fest, was sie in der Ausbildung gelernt haben.",
      tipp: "Fachwort: Ausbildungsnachweis.",
      loesung: "BERICHTSHEFT",
      bestaetigung: "Genau! Das Berichtsheft dokumentiert die vermittelten Inhalte und hilft, Lücken früh zu erkennen.",
    },
    {
      nummer: 16,
      hinweis: "Anfangsphase, in der beide Seiten prüfen, ob die Ausbildung passt.",
      tipp: "Zwischengespräche helfen, sie gut zu nutzen.",
      loesung: "PROBEZEIT",
      bestaetigung: "Richtig! In der Probezeit lohnen sich Zwischengespräche und eine gute Dokumentation, damit die Entscheidung am Ende fundiert ist.",
    },
    // HF3 — Ausbildung durchführen
    {
      nummer: 17,
      hinweis: "Konkrete und zeitnahe Rückmeldung zu beobachtbarem Verhalten.",
      tipp: "Englisches Wort; es geht in beide Richtungen.",
      loesung: "FEEDBACK",
      bestaetigung: "Genau! Gutes Feedback ist konkret, zeitnah und zweiseitig.",
    },
    {
      nummer: 18,
      hinweis: "Rückmeldungsform: Lob, dann Verbesserungshinweis, dann ermutigender Abschluss.",
      tipp: "Erinnert an ein belegtes Brot.",
      loesung: "SANDWICH",
      bestaetigung: "Richtig! Die Sandwich-Methode sollte nicht schematisch genutzt werden, denn unehrliches Lob durchschauen Azubis schnell.",
    },
    {
      nummer: 19,
      hinweis: "Methode, bei der Leitfragen zum selbstständigen Erarbeiten führen.",
      tipp: "Passt für offene Aufgaben, z. B. ein Netzwerkproblem.",
      loesung: "LEITTEXT",
      bestaetigung: "Genau! Bei der Leittextmethode erarbeiten, planen und kontrollieren Azubis vieles selbst.",
    },
    {
      nummer: 20,
      hinweis: "Größeres Vorhaben, das Azubis von der Zielsetzung bis zur Präsentation durchführen.",
      tipp: "Beispiel: ein Tag der offenen Tür.",
      loesung: "PROJEKT",
      bestaetigung: "Richtig! Die Projektmethode eignet sich für größere, abteilungsübergreifende Vorhaben.",
    },
    {
      nummer: 21,
      hinweis: "Stufe der Unterweisung: Die Ausbilderin zeigt den Schritt und erklärt ihn.",
      tipp: "Es ist die zweite Stufe.",
      loesung: "VORMACHEN",
      bestaetigung: "Genau! Erst vormachen und erklären, dann nachmachen lassen und üben lassen.",
    },
    {
      nummer: 22,
      hinweis: "Lernzielbereich für Wissen, Verstehen und Denken.",
      tipp: "Merkhilfe: der Kopf.",
      loesung: "KOGNITIV",
      bestaetigung: "Richtig! Kognitive Lernziele betreffen Wissen und Zusammenhänge.",
    },
    {
      nummer: 23,
      hinweis: "Lernzielbereich für Einstellungen, Werte und Haltungen.",
      tipp: "Merkhilfe: das Herz.",
      loesung: "AFFEKTIV",
      bestaetigung: "Genau! Haltungen entwickeln sich durch Vorbild, Erfahrung im Team, Feedback und gemeinsame Reflexion.",
    },
    {
      nummer: 24,
      hinweis: "Allgemeinstes Lernziel; es gibt nur die große Richtung vor.",
      tipp: "Konkreter sind Grobziel und Feinziel.",
      loesung: "RICHTZIEL",
      bestaetigung: "Richtig! Vom Richtziel über das Grobziel bis zum Feinziel werden Lernziele immer konkreter.",
    },
    {
      nummer: 25,
      hinweis: "Beurteilungsfehler: Ein auffälliges Merkmal überstrahlt alle anderen.",
      tipp: "Auch Überstrahlungseffekt genannt.",
      loesung: "HALO",
      bestaetigung: "Genau! Beim Halo-Effekt färbt ein einzelnes Merkmal das ganze Urteil.",
    },
    {
      nummer: 26,
      hinweis: "Beurteilungsfehler: Man bewertet insgesamt zu gut.",
      tipp: "Das Gegenstück ist der Strengefehler.",
      loesung: "MILDE",
      bestaetigung: "Richtig! Beim Mildefehler wird zu großzügig bewertet, etwa um Ärger zu vermeiden.",
    },
    {
      nummer: 27,
      hinweis: "Beurteilungsfehler: Zuletzt Beobachtetes zählt viel zu stark.",
      tipp: "Englisch; deutsch Nähe- oder Aktualitätseffekt.",
      loesung: "RECENCY",
      bestaetigung: "Genau! Wer über das ganze Jahr beurteilt, notiert Beobachtungen fortlaufend.",
    },
    {
      nummer: 28,
      hinweis: "Spannung zwischen Beteiligten, die früh erkannt und geklärt werden sollte.",
      tipp: "Hilfreich: ein moderiertes Klärungsgespräch.",
      loesung: "KONFLIKT",
      bestaetigung: "Richtig! Ausbilder:innen sollten Konflikte rechtzeitig erkennen und auf eine Lösung hinwirken, statt sie auszusitzen.",
    },
    // HF4 — Ausbildung abschließen
    {
      nummer: 29,
      hinweis: "Schriftliche Bestätigung des Betriebs über die absolvierte Ausbildung.",
      tipp: "Es kann einfach oder qualifiziert sein.",
      loesung: "ZEUGNIS",
      bestaetigung: "Genau! Das Ausbildungszeugnis stellt der Betrieb aus, das Prüfungszeugnis die Kammer.",
    },
    {
      nummer: 30,
      hinweis: "Am Ende der Ausbildung zeigen Azubis hier, was sie gelernt haben.",
      tipp: "Wird oft gestreckt in zwei Teile.",
      loesung: "PRUEFUNG",
      bestaetigung: "Richtig! Die Vorbereitung darauf begleitet die gesamte Ausbildungszeit, nicht nur die letzten Wochen.",
    },
    {
      nummer: 31,
      hinweis: "Formale Meldung bei der Kammer; der Termin darf nicht verpasst werden.",
      tipp: "Dafür führt Kelvinar eine zentrale Terminübersicht.",
      loesung: "ANMELDUNG",
      bestaetigung: "Genau! Die Anmeldung zur Abschlussprüfung gehört zu den Aufgaben des Ausbildungsbetriebs.",
    },
    {
      nummer: 32,
      hinweis: "Azubi bleibt nach bestandener Prüfung als Beschäftigte:r im Betrieb.",
      tipp: "Darüber spricht man im Perspektivgespräch.",
      loesung: "UEBERNAHME",
      bestaetigung: "Richtig! Die Frage der Übernahme gehört zu den Perspektiven, die Ausbildende gegen Ende der Ausbildung aufzeigen.",
    },
    {
      nummer: 33,
      hinweis: "Fortbildung der Kammer als Aufstieg, z. B. im kaufmännischen Bereich.",
      tipp: "Technisches Gegenstück: Meister oder Techniker.",
      loesung: "FACHWIRT",
      bestaetigung: "Genau! Fachwirt-Fortbildungen bauen auf der Erstausbildung und Berufserfahrung auf.",
    },
    {
      nummer: 34,
      hinweis: "Grundsatz fürs Zeugnis: Die Aussagen müssen inhaltlich stimmen.",
      tipp: "Ein zweiter Grundsatz ist die Klarheit.",
      loesung: "WAHRHEIT",
      bestaetigung: "Richtig! Zeugniswahrheit, Zeugnisklarheit und ein wohlwollender Gesamtton sind die Grundsätze für ein Zeugnis.",
    },
  ],
  falschEinfachFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und denke daran, was du in der Ausbildung der Ausbilder gelernt hast.",
  falschAnspruchsvollFeedback: "Das passt hier noch nicht. Lies den Hinweis erneut und prüfe auch die Buchstaben an den Kreuzungen.",
  unvollstaendigFeedback: "Hier fehlen noch Buchstaben. Du kannst das Wort weiter ausfüllen.",
  abschlussmeldung:
    "Geschafft! Du hast zehn Begriffe aus der Ausbildung der Ausbilder wiederholt, von der Planung bis zum Abschluss. Jedes Rätsel ist anders — spiel gern noch eins!",
};
