import type { MemoryPayload } from "@edukedo/shared";

/**
 * F-193 (Wiederspielbarkeit, Nutzer-Vorgabe vom 06.10.2026): Memory-Pool „Handelsfachwirt".
 * Vier thematische Runden mit je zehn Paaren (Begriff ↔ Bedeutung) aus der Kurstheorie (content/handelsfachwirt/);
 * pro Spiel zieht der Server je Runde sechs Paare. Der Außenhandel bleibt bewusst ausgespart (keine Zoll- und
 * Außenwirtschaftsdetails). Inhaltlich ein Entwurf: keine Paragrafen, Zahlenwerte oder Fristen; Freigabe erst nach der Fachprüfung.
 */
export const memoryHandel: MemoryPayload = {
  paareProRunde: 6,
  runden: [
    {
      nummer: 1,
      titel: "Idee, Finanzen und Risiko",
      abschlussmeldung: "Geschafft! Du kennst jetzt wichtige Begriffe zu Geschäftsidee, Finanzierung, Controlling und Risikomanagement.",
    },
    {
      nummer: 2,
      titel: "Führung, Personal und Arbeitsschutz",
      abschlussmeldung: "Geschafft! Du erkennst jetzt Führungsstile, Methoden der Ausbildung, Personalplanung und Arbeitsschutz.",
    },
    {
      nummer: 3,
      titel: "Markt, Sortiment, Werbung und Fläche",
      abschlussmeldung: "Geschafft! Du kannst jetzt Begriffe aus Marktanalyse, Sortiment, Werbung und Flächenplanung zuordnen.",
    },
    {
      nummer: 4,
      titel: "Einkauf, Lager und Logistik",
      abschlussmeldung: "Geschafft! Du kennst jetzt zentrale Begriffe aus Bedarfsermittlung, Lager, Einkauf und Verhandlung.",
    },
  ],
  paare: [
    // Runde 1 — Idee, Finanzen und Risiko (HB1)
    {
      nummer: 1,
      runde: 1,
      begriff: "Ansoff-Matrix",
      bedeutung: "Ordnet Wachstum nach Produkten und Märkten",
      bestaetigung: "Richtig! Die Ansoff-Matrix unterscheidet vier Wachstumsstrategien, je nachdem ob Produkt und Markt vorhanden oder neu sind.",
    },
    {
      nummer: 2,
      runde: 1,
      begriff: "Executive Summary",
      bedeutung: "Kurze Zusammenfassung am Anfang des Businessplans",
      bestaetigung: "Genau! Sie steht zuerst im Businessplan, wird aber meist zuletzt geschrieben.",
    },
    {
      nummer: 3,
      runde: 1,
      begriff: "Selbstfinanzierung",
      bedeutung: "Gewinne bleiben im Unternehmen statt ausgeschüttet",
      bestaetigung: "Richtig! Das ist eine Form der Innenfinanzierung, bei der kein Kapital von außen zufließt.",
    },
    {
      nummer: 4,
      runde: 1,
      begriff: "Kontokorrentkredit",
      bedeutung: "Kurzfristiger Kredit auf dem Geschäftskonto",
      bestaetigung: "Genau! Er überbrückt Engpässe, zum Beispiel bei saisonalen Schwankungen im Handel.",
    },
    {
      nummer: 5,
      runde: 1,
      begriff: "Lieferantenkredit",
      bedeutung: "Ware kommt sofort, bezahlt wird erst später",
      bestaetigung: "Richtig! Das Zahlungsziel des Lieferanten ist wirtschaftlich ein kurzfristiger Kredit.",
    },
    {
      nummer: 6,
      runde: 1,
      begriff: "Leverage-Effekt",
      bedeutung: "Fremdkapital kann die Eigenkapitalrendite steigern",
      bestaetigung: "Genau! Das funktioniert nur, solange die Gesamtkapitalrendite über dem Fremdkapitalzins liegt.",
    },
    {
      nummer: 7,
      runde: 1,
      begriff: "Balanced Scorecard",
      bedeutung: "Ergänzt Finanzzahlen um drei weitere Perspektiven",
      bestaetigung: "Richtig! Dazu zählen die Kundensicht, die interne Prozesssicht und die Lern- und Entwicklungssicht.",
    },
    {
      nummer: 8,
      runde: 1,
      begriff: "Break-Even-Point",
      bedeutung: "Gewinnschwelle: Erlöse gleich Gesamtkosten",
      bestaetigung: "Genau! Unterhalb dieser Absatzmenge entsteht ein Verlust, oberhalb ein Gewinn.",
    },
    {
      nummer: 9,
      runde: 1,
      begriff: "Risikomatrix",
      bedeutung: "Ordnet Risiken nach Wahrscheinlichkeit und Schaden",
      bestaetigung: "Richtig! So lässt sich erkennen, welche Risiken zuerst Handlungsbedarf auslösen.",
    },
    {
      nummer: 10,
      runde: 1,
      begriff: "Risikoüberwälzung",
      bedeutung: "Risiko geht z. B. per Versicherung auf Dritte über",
      bestaetigung: "Genau! Typisches Beispiel ist die Transportversicherung für importierte Ware.",
    },
    // Runde 2 — Führung, Personal und Arbeitsschutz (HB2)
    {
      nummer: 11,
      runde: 2,
      begriff: "Laissez-faire",
      bedeutung: "Führung mit viel Freiheit und kaum Eingriffen",
      bestaetigung: "Richtig! Das kann Kreativität fördern, birgt aber das Risiko von Orientierungslosigkeit.",
    },
    {
      nummer: 12,
      runde: 2,
      begriff: "Situatives Führen",
      bedeutung: "Verhalten richtet sich nach Aufgabe und Reifegrad",
      bestaetigung: "Genau! Eine neue Auszubildende braucht mehr Anleitung als eine erfahrene Verkäuferin.",
    },
    {
      nummer: 13,
      runde: 2,
      begriff: "Management by Exception",
      bedeutung: "Chefs greifen nur bei Abweichungen vom Normalfall ein",
      bestaetigung: "Richtig! Im Normalbetrieb arbeiten die Mitarbeitenden selbständig.",
    },
    {
      nummer: 14,
      runde: 2,
      begriff: "Vier-Seiten-Modell",
      bedeutung: "Sachinhalt, Selbstoffenbarung, Beziehung und Appell",
      bestaetigung: "Genau! Jede Nachricht enthält diese vier Aspekte, und Missverständnisse entstehen oft, wenn verschiedene Ohren betont werden.",
    },
    {
      nummer: 15,
      runde: 2,
      begriff: "Hygienefaktoren",
      bedeutung: "Fehlen sie, entsteht Unzufriedenheit",
      bestaetigung: "Richtig! Gehalt und Arbeitsbedingungen gehören dazu; allein motivieren sie aber noch nicht.",
    },
    {
      nummer: 16,
      runde: 2,
      begriff: "Vier-Stufen-Methode",
      bedeutung: "Vorbereiten, Vormachen, Nachmachen, Üben",
      bestaetigung: "Genau! Sie eignet sich gut, um Arbeitsschritte wie das Kassieren zu vermitteln.",
    },
    {
      nummer: 17,
      runde: 2,
      begriff: "Off-the-Job",
      bedeutung: "Weiterbildung losgelöst vom Arbeitsplatz",
      bestaetigung: "Richtig! Ein externes Seminar für angehende Filialleitungen ist ein Beispiel dafür.",
    },
    {
      nummer: 18,
      runde: 2,
      begriff: "Nettopersonalbedarf",
      bedeutung: "Bruttobedarf minus vorhandenes Personal",
      bestaetigung: "Genau! Er zeigt die tatsächliche Lücke, die noch gedeckt werden muss.",
    },
    {
      nummer: 19,
      runde: 2,
      begriff: "Gefährdungsbeurteilung",
      bedeutung: "Gefahren am Arbeitsplatz systematisch ermitteln",
      bestaetigung: "Richtig! Sie ist kein einmaliger Vorgang und wird bei Veränderungen aktualisiert.",
    },
    {
      nummer: 20,
      runde: 2,
      begriff: "Sicherheitsbeauftragte",
      bedeutung: "Beschäftigte, die Kolleg:innen bei der Sicherheit unterstützen",
      bestaetigung: "Genau! Sie unterstützen den Arbeitgeber in ihrem Arbeitsbereich, haben aber keine Weisungsbefugnis.",
    },
    // Runde 3 — Markt, Sortiment, Werbung und Fläche (HB3, WB1)
    {
      nummer: 21,
      runde: 3,
      begriff: "Primärforschung",
      bedeutung: "Neue Daten, die selbst für ein Ziel erhoben werden",
      bestaetigung: "Richtig! Eine Kundenbefragung in den Filialen ist ein Beispiel dafür.",
    },
    {
      nummer: 22,
      runde: 3,
      begriff: "Sekundärforschung",
      bedeutung: "Auswertung bereits vorhandener Daten",
      bestaetigung: "Genau! Sie ist meist günstiger und schneller, passt aber nicht immer exakt zur Frage.",
    },
    {
      nummer: 23,
      runde: 3,
      begriff: "Marktsegmentierung",
      bedeutung: "Gesamtmarkt in ähnliche Teilgruppen gliedern",
      bestaetigung: "Richtig! Sie ist die Voraussetzung dafür, Kundengruppen gezielt anzusprechen.",
    },
    {
      nummer: 24,
      runde: 3,
      begriff: "Benchmarking",
      bedeutung: "Vergleich mit dem Klassenbesten der Branche",
      bestaetigung: "Genau! So lassen sich Verbesserungsmöglichkeiten erkennen.",
    },
    {
      nummer: 25,
      runde: 3,
      begriff: "Sortimentstiefe",
      bedeutung: "Wie viele Varianten eine Warengruppe bietet",
      bestaetigung: "Richtig! Die Breite zählt dagegen die Warengruppen.",
    },
    {
      nummer: 26,
      runde: 3,
      begriff: "ABC-Analyse",
      bedeutung: "Teilt Artikel nach ihrem Umsatzanteil ein",
      bestaetigung: "Genau! A-Artikel bringen viel Umsatz und werden besonders eng überwacht.",
    },
    {
      nummer: 27,
      runde: 3,
      begriff: "Werbeträger",
      bedeutung: "Das Medium, über das Werbung ihre Zielgruppe erreicht",
      bestaetigung: "Richtig! Eine Wochenzeitung ist ein Werbeträger, der Flyer darin das Werbemittel.",
    },
    {
      nummer: 28,
      runde: 3,
      begriff: "Omnichannel",
      bedeutung: "Online und Filiale nahtlos verbunden",
      bestaetigung: "Genau! Online bestellen und in der Filiale abholen ist ein typisches Beispiel.",
    },
    {
      nummer: 29,
      runde: 3,
      begriff: "Planogramm",
      bedeutung: "Zeigt, welcher Artikel wo im Regal steht",
      bestaetigung: "Richtig! So sieht die Warenpräsentation in allen Filialen einheitlich aus.",
    },
    {
      nummer: 30,
      runde: 3,
      begriff: "Category Captain",
      bedeutung: "Lieferant, der bei der Warengruppe beratend hilft",
      bestaetigung: "Genau! Die Entscheidung über die Listung bleibt beim eigenen Einkauf.",
    },
    // Runde 4 — Einkauf, Lager und Logistik (HB4, WB2, WB3)
    {
      nummer: 31,
      runde: 4,
      begriff: "XYZ-Analyse",
      bedeutung: "Ordnet Artikel nach Vorhersagbarkeit des Bedarfs",
      bestaetigung: "Richtig! X-Artikel sind gut planbar, Z-Artikel kaum.",
    },
    {
      nummer: 32,
      runde: 4,
      begriff: "Meldebestand",
      bedeutung: "Erreicht der Bestand ihn, wird nachbestellt",
      bestaetigung: "Genau! Er ergibt sich aus Sicherheitsbestand und erwartetem Verbrauch bis zur Lieferung.",
    },
    {
      nummer: 33,
      runde: 4,
      begriff: "Nachorder",
      bedeutung: "Kleine, kurzfristige Nachbestellung in der Saison",
      bestaetigung: "Richtig! Bei einmalig produzierten Trendartikeln ist sie oft gar nicht mehr möglich.",
    },
    {
      nummer: 34,
      runde: 4,
      begriff: "Cross-Docking",
      bedeutung: "Ware wird fast ohne Lagerung direkt weitergeleitet",
      bestaetigung: "Genau! Das spart Lagerzeit, verlangt aber genau abgestimmte Ankunfts- und Abfahrtszeiten.",
    },
    {
      nummer: 35,
      runde: 4,
      begriff: "Konsignationslager",
      bedeutung: "Ware des Lieferanten, bezahlt erst bei Entnahme",
      bestaetigung: "Richtig! Die Ware steht beim Abnehmer, gehört aber bis zur Entnahme dem Lieferanten.",
    },
    {
      nummer: 36,
      runde: 4,
      begriff: "Single Sourcing",
      bedeutung: "Nur ein Lieferant für einen Artikel",
      bestaetigung: "Genau! Das bündelt die Menge, macht aber bei einem Ausfall sehr abhängig.",
    },
    {
      nummer: 37,
      runde: 4,
      begriff: "Kraljic-Matrix",
      bedeutung: "Gewinnauswirkung und Versorgungsrisiko als Achsen",
      bestaetigung: "Richtig! Daraus ergeben sich Standard-, Hebel-, Engpass- und strategische Produkte.",
    },
    {
      nummer: 38,
      runde: 4,
      begriff: "BATNA",
      bedeutung: "Die beste eigene Alternative ohne Einigung",
      bestaetigung: "Genau! Ein geprüfter Zweitlieferant stärkt die Position in der Verhandlung.",
    },
    {
      nummer: 39,
      runde: 4,
      begriff: "Compliance",
      bedeutung: "Einhalten von Gesetzen und internen Regeln",
      bestaetigung: "Richtig! Im Einkauf geht es dabei auch um Korruptionsprävention und Sorgfalt in der Lieferkette.",
    },
    {
      nummer: 40,
      runde: 4,
      begriff: "Kapitalwertmethode",
      bedeutung: "Zahlungen werden abgezinst; positiv heißt vorteilhaft",
      bestaetigung: "Genau! Als dynamisches Verfahren berücksichtigt sie, wann die Zahlungen anfallen.",
    },
  ],
  falschesPaarFeedback: "Das ist noch kein Paar. Schau dir beide Karten genau an und versuche es erneut.",
  abschlussmeldung:
    "Geschafft! Du hast Handelsbegriffe aus allen Bereichen richtig zugeordnet. Mit „Noch einmal spielen“ bekommst du neue Karten aus dem Kartenvorrat.",
};
